//noinspection SpellCheckingInspection

plugins {
    id 'java'
    id 'application'
    id 'org.gradlex.extra-java-module-info' version '1.14'
}

group = 'com.losi.create'
version = '1.0.0-a1'

import org.gradle.internal.os.OperatingSystem

project.ext.lwjglVersion = "3.4.1"
project.ext.jomlVersion = "1.10.8"
project.ext['joml-primitivesVersion'] = "1.10.0"
project.ext.steamworks4jVersion = "1.10.0"
project.ext['steamworks4j-serverVersion'] = "1.10.0"
project.ext['querz-NBTversion'] = "6.1"

switch (OperatingSystem.current()) {
    case OperatingSystem.LINUX:
        //noinspection GroovyAssignabilityCheck
        project.ext.lwjglNatives = "natives-linux"
        def osArch = System.getProperty("os.arch")
        if (osArch.startsWith("arm") || osArch.startsWith("aarch64")) {
            project.ext.lwjglNatives += osArch.contains("64") || osArch.startsWith("armv8") ? "-arm64" : "-arm32"
        } else if  (osArch.startsWith("ppc")) {
            project.ext.lwjglNatives += "-ppc64le"
        } else if  (osArch.startsWith("riscv")) {
            project.ext.lwjglNatives += "-riscv64"
        }
        break
    case OperatingSystem.MAC_OS:
        //noinspection GroovyAssignabilityCheck
        project.ext.lwjglNatives = System.getProperty("os.arch").startsWith("aarch64") ? "natives-macos-arm64" : "natives-macos"
        break
    case OperatingSystem.WINDOWS:
        def osArch = System.getProperty("os.arch")
        //noinspection GroovyAssignabilityCheck
        project.ext.lwjglNatives = osArch.contains("64")
                ? "natives-windows${osArch.startsWith("aarch64") ? "-arm64" : ""}"
                : "natives-windows-x86"
        break
}

dependencies {
    // ---------- Default ----------
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // ---------- LWJGL setup ----------
    implementation platform("org.lwjgl:lwjgl-bom:$lwjglVersion")

    ["-egl", "-fmod", "-jawt", "-odbc", "-opencl", "-renderdoc"].each {
        implementation "org.lwjgl:lwjgl$it"
    }

    ["", "-assimp", "-bgfx", "-freetype", "-glfw", "-harfbuzz", "-hwloc", "-jemalloc", "-ktx", "-llvm", "-lmdb", "-lz4",
     "-meshoptimizer", "-msdfgen", "-nanovg", "-nfd", "-nuklear", "-openal", "-opengl", "-opengles", "-openxr", "-opus",
     "-par", "-remotery", "-rpmalloc", "-sdl", "-shaderc", "-spng", "-spvc", "-stb", "-tinyexr", "-tinyfd", "-vma", "-vulkan",
     "-xxhash", "-yoga", "-zstd"].each {
        implementation "org.lwjgl:lwjgl$it"
        if (it != "-vulkan" || lwjglNatives == "natives-macos" || lwjglNatives == "natives-macos-arm64")
            implementation "org.lwjgl:lwjgl$it::$lwjglNatives"
    }

    // OpenGL Math
    implementation "org.joml:joml:${jomlVersion}"
    implementation "org.joml:joml-primitives:${project.ext['joml-primitivesVersion']}"

    // Steam
    implementation "com.code-disaster.steamworks4j:steamworks4j:${steamworks4jVersion}"
    implementation "com.code-disaster.steamworks4j:steamworks4j-server:${project.ext['steamworks4j-serverVersion']}"

    //NBT
    implementation "com.github.Querz:NBT:${project.ext['querz-NBTversion']}"

    //Annotations
    compileOnly 'org.jetbrains:annotations:26.0.2'

    //Koloboke
    compileOnly 'com.koloboke:koloboke-api-jdk8:1.0.0'
    runtimeOnly 'com.koloboke:koloboke-impl-jdk8:1.0.0'
}

tasks.register('createProperties') {
    dependsOn processResources
    def propsFileProvider = layout.buildDirectory.file("resources/main/version.properties")
    outputs.file(propsFileProvider)

    // Declare inputs so Gradle knows when to rerun
    inputs.property("create", project.version.toString())
    inputs.property("lwjgl", project.ext['lwjglVersion'] as String)
    inputs.property("joml", project.ext['steamworks4j-serverVersion'] as String)
    inputs.property("joml-primitives", project.ext['joml-primitivesVersion'] as String)
    inputs.property("steamworks", project.ext['steamworks4jVersion'] as String)
    inputs.property("steamworks-server", project.ext['steamworks4j-serverVersion'] as String)
    inputs.property("querz-NBT", project.ext['querz-NBTversion'] as String)

    doLast {
        def propsFile = propsFileProvider.get().asFile
        propsFile.parentFile.mkdirs()
        Properties p = new Properties()
        p['create-version'] = inputs.properties['create']
        p['lwjgl-version'] = inputs.properties['lwjgl']
        p['joml-version'] = inputs.properties['joml']
        p['joml-primitives-version'] = inputs.properties['joml-primitives']
        p['steamworks4j-version'] = inputs.properties['steamworks']
        p['steamworks4j-server-version'] = inputs.properties['steamworks-server']
        p['querz-NBT-version'] = inputs.properties['querz-NBT']
        propsFile.withWriter { w -> p.store(w, null) }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs += '-Xlint:-incubating'
}

extraJavaModuleInfo {
    failOnMissingModuleInfo = false
    automaticModule("com.github.Querz:NBT", 'nbt.querz')
    automaticModule("com.koloboke:koloboke-api-jdk8", 'koloboke.api.jdk8')
    module("org.jetbrains:annotations", "org.jetbrains.annotations") {
        patchRealModule()
        preserveExisting()
        exports 'org.jetbrains.annotations'
    }
    automaticModule('com.code-disaster.steamworks4j:steamworks4j', 'steamworks4j') {
        mergeJar("com.code-disaster.steamworks4j:steamworks4j-server")
    }
}

tasks.named('classes') {
    dependsOn(tasks.named('createProperties'))
}

run {
    args = []
}

application {
    applicationDefaultJvmArgs += [ '--enable-native-access=org.lwjgl', '--enable-native-access=org.lwjgl.opengl' ]
    mainClass = 'com.losi.create.internal.Start'
    mainModule = 'com.losi.create'
}

test {
    useJUnitPlatform()
}