@file:Suppress("unused", "SpellCheckingInspection")
package com.losi.create.utility.joml

import org.joml.*

fun Vector3f.toTriple() = Triple(this.x, this.y, this.z)
fun Triple<Float, Float, Float>.toVector() = Vector3f(this.first, this.second, this.third)

// ===================================== XYZ =====================================
val Vector3f.xx get() = Vector2f(this.x, this.x)
var Vector3f.xy get() = Vector2f(this.x, this.y); set(it) { this.x = it.x; this.y = it.y }
var Vector3f.xz get() = Vector2f(this.x, this.z); set(it) { this.x = it.x; this.z = it.y }
var Vector3f.yx get() = Vector2f(this.y, this.x); set(it) { this.y = it.x; this.x = it.y }
val Vector3f.yy get() = Vector2f(this.y, this.y)
var Vector3f.yz get() = Vector2f(this.y, this.z); set(it) { this.y = it.x; this.z = it.y }
var Vector3f.zx get() = Vector2f(this.z, this.x); set(it) { this.z = it.x; this.x = it.y }
var Vector3f.zy get() = Vector2f(this.z, this.y); set(it) { this.z = it.x; this.y = it.y }
val Vector3f.zz get() = Vector2f(this.z, this.z)

val Vector3f.xxx get() = Vector3f(this.x, this.x, this.x)
val Vector3f.xxy get() = Vector3f(this.x, this.x, this.y)
val Vector3f.xxz get() = Vector3f(this.x, this.x, this.z)
val Vector3f.xyx get() = Vector3f(this.x, this.y, this.x)
val Vector3f.xyy get() = Vector3f(this.x, this.y, this.y)
var Vector3f.xyz get() = Vector3f(this.x, this.y, this.z); set(it) { this.x = it.x; this.y = it.y; this.z = it.z }
val Vector3f.xzx get() = Vector3f(this.x, this.z, this.x)
var Vector3f.xzy get() = Vector3f(this.x, this.z, this.y); set(it) { this.x = it.x; this.z = it.y; this.y = it.z }
val Vector3f.xzz get() = Vector3f(this.x, this.z, this.z)
val Vector3f.yxx get() = Vector3f(this.y, this.x, this.x)
val Vector3f.yxy get() = Vector3f(this.y, this.x, this.y)
var Vector3f.yxz get() = Vector3f(this.y, this.x, this.z); set(it) { this.y = it.x; this.x = it.y; this.z = it.z }
val Vector3f.yyx get() = Vector3f(this.y, this.y, this.x)
val Vector3f.yyy get() = Vector3f(this.y, this.y, this.y)
val Vector3f.yyz get() = Vector3f(this.y, this.y, this.z)
var Vector3f.yzx get() = Vector3f(this.y, this.z, this.x); set(it) { this.y = it.x; this.z = it.y; this.x = it.z }
val Vector3f.yzy get() = Vector3f(this.y, this.z, this.y)
val Vector3f.yzz get() = Vector3f(this.y, this.z, this.z)
val Vector3f.zxx get() = Vector3f(this.z, this.x, this.x)
var Vector3f.zxy get() = Vector3f(this.z, this.x, this.y); set(it) { this.z = it.x; this.x = it.y; this.y = it.z }
val Vector3f.zxz get() = Vector3f(this.z, this.x, this.z)
var Vector3f.zyx get() = Vector3f(this.z, this.y, this.x); set(it) { this.z = it.x; this.y = it.y; this.x = it.z }
val Vector3f.zyy get() = Vector3f(this.z, this.y, this.y)
val Vector3f.zyz get() = Vector3f(this.z, this.y, this.z)
val Vector3f.zzx get() = Vector3f(this.z, this.z, this.x)
val Vector3f.zzy get() = Vector3f(this.z, this.z, this.y)
val Vector3f.zzz get() = Vector3f(this.z, this.z, this.z)

val Vector3f.xxxx get() = Vector4f(this.x, this.x, this.x, this.x)
val Vector3f.xxxy get() = Vector4f(this.x, this.x, this.x, this.y)
val Vector3f.xxxz get() = Vector4f(this.x, this.x, this.x, this.z)
val Vector3f.xxyx get() = Vector4f(this.x, this.x, this.y, this.x)
val Vector3f.xxyy get() = Vector4f(this.x, this.x, this.y, this.y)
val Vector3f.xxyz get() = Vector4f(this.x, this.x, this.y, this.z)
val Vector3f.xxzx get() = Vector4f(this.x, this.x, this.z, this.x)
val Vector3f.xxzy get() = Vector4f(this.x, this.x, this.z, this.y)
val Vector3f.xxzz get() = Vector4f(this.x, this.x, this.z, this.z)
val Vector3f.xyxx get() = Vector4f(this.x, this.y, this.x, this.x)
val Vector3f.xyxy get() = Vector4f(this.x, this.y, this.x, this.y)
val Vector3f.xyxz get() = Vector4f(this.x, this.y, this.x, this.z)
val Vector3f.xyyx get() = Vector4f(this.x, this.y, this.y, this.x)
val Vector3f.xyyy get() = Vector4f(this.x, this.y, this.y, this.y)
val Vector3f.xyyz get() = Vector4f(this.x, this.y, this.y, this.z)
val Vector3f.xyzx get() = Vector4f(this.x, this.y, this.z, this.x)
val Vector3f.xyzy get() = Vector4f(this.x, this.y, this.z, this.y)
val Vector3f.xyzz get() = Vector4f(this.x, this.y, this.z, this.z)
val Vector3f.xzxx get() = Vector4f(this.x, this.z, this.x, this.x)
val Vector3f.xzxy get() = Vector4f(this.x, this.z, this.x, this.y)
val Vector3f.xzxz get() = Vector4f(this.x, this.z, this.x, this.z)
val Vector3f.xzyx get() = Vector4f(this.x, this.z, this.y, this.x)
val Vector3f.xzyy get() = Vector4f(this.x, this.z, this.y, this.y)
val Vector3f.xzyz get() = Vector4f(this.x, this.z, this.y, this.z)
val Vector3f.xzzx get() = Vector4f(this.x, this.z, this.z, this.x)
val Vector3f.xzzy get() = Vector4f(this.x, this.z, this.z, this.y)
val Vector3f.xzzz get() = Vector4f(this.x, this.z, this.z, this.z)
val Vector3f.yxxx get() = Vector4f(this.y, this.x, this.x, this.x)
val Vector3f.yxxy get() = Vector4f(this.y, this.x, this.x, this.y)
val Vector3f.yxxz get() = Vector4f(this.y, this.x, this.x, this.z)
val Vector3f.yxyx get() = Vector4f(this.y, this.x, this.y, this.x)
val Vector3f.yxyy get() = Vector4f(this.y, this.x, this.y, this.y)
val Vector3f.yxyz get() = Vector4f(this.y, this.x, this.y, this.z)
val Vector3f.yxzx get() = Vector4f(this.y, this.x, this.z, this.x)
val Vector3f.yxzy get() = Vector4f(this.y, this.x, this.z, this.y)
val Vector3f.yxzz get() = Vector4f(this.y, this.x, this.z, this.z)
val Vector3f.yyxx get() = Vector4f(this.y, this.y, this.x, this.x)
val Vector3f.yyxy get() = Vector4f(this.y, this.y, this.x, this.y)
val Vector3f.yyxz get() = Vector4f(this.y, this.y, this.x, this.z)
val Vector3f.yyyx get() = Vector4f(this.y, this.y, this.y, this.x)
val Vector3f.yyyy get() = Vector4f(this.y, this.y, this.y, this.y)
val Vector3f.yyyz get() = Vector4f(this.y, this.y, this.y, this.z)
val Vector3f.yyzx get() = Vector4f(this.y, this.y, this.z, this.x)
val Vector3f.yyzy get() = Vector4f(this.y, this.y, this.z, this.y)
val Vector3f.yyzz get() = Vector4f(this.y, this.y, this.z, this.z)
val Vector3f.yzxx get() = Vector4f(this.y, this.z, this.x, this.x)
val Vector3f.yzxy get() = Vector4f(this.y, this.z, this.x, this.y)
val Vector3f.yzxz get() = Vector4f(this.y, this.z, this.x, this.z)
val Vector3f.yzyx get() = Vector4f(this.y, this.z, this.y, this.x)
val Vector3f.yzyy get() = Vector4f(this.y, this.z, this.y, this.y)
val Vector3f.yzyz get() = Vector4f(this.y, this.z, this.y, this.z)
val Vector3f.yzzx get() = Vector4f(this.y, this.z, this.z, this.x)
val Vector3f.yzzy get() = Vector4f(this.y, this.z, this.z, this.y)
val Vector3f.yzzz get() = Vector4f(this.y, this.z, this.z, this.z)
val Vector3f.zxxx get() = Vector4f(this.z, this.x, this.x, this.x)
val Vector3f.zxxy get() = Vector4f(this.z, this.x, this.x, this.y)
val Vector3f.zxxz get() = Vector4f(this.z, this.x, this.x, this.z)
val Vector3f.zxyx get() = Vector4f(this.z, this.x, this.y, this.x)
val Vector3f.zxyy get() = Vector4f(this.z, this.x, this.y, this.y)
val Vector3f.zxyz get() = Vector4f(this.z, this.x, this.y, this.z)
val Vector3f.zxzx get() = Vector4f(this.z, this.x, this.z, this.x)
val Vector3f.zxzy get() = Vector4f(this.z, this.x, this.z, this.y)
val Vector3f.zxzz get() = Vector4f(this.z, this.x, this.z, this.z)
val Vector3f.zyxx get() = Vector4f(this.z, this.y, this.x, this.x)
val Vector3f.zyxy get() = Vector4f(this.z, this.y, this.x, this.y)
val Vector3f.zyxz get() = Vector4f(this.z, this.y, this.x, this.z)
val Vector3f.zyyx get() = Vector4f(this.z, this.y, this.y, this.x)
val Vector3f.zyyy get() = Vector4f(this.z, this.y, this.y, this.y)
val Vector3f.zyyz get() = Vector4f(this.z, this.y, this.y, this.z)
val Vector3f.zyzx get() = Vector4f(this.z, this.y, this.z, this.x)
val Vector3f.zyzy get() = Vector4f(this.z, this.y, this.z, this.y)
val Vector3f.zyzz get() = Vector4f(this.z, this.y, this.z, this.z)
val Vector3f.zzxx get() = Vector4f(this.z, this.z, this.x, this.x)
val Vector3f.zzxy get() = Vector4f(this.z, this.z, this.x, this.y)
val Vector3f.zzxz get() = Vector4f(this.z, this.z, this.x, this.z)
val Vector3f.zzyx get() = Vector4f(this.z, this.z, this.y, this.x)
val Vector3f.zzyy get() = Vector4f(this.z, this.z, this.y, this.y)
val Vector3f.zzyz get() = Vector4f(this.z, this.z, this.y, this.z)
val Vector3f.zzzx get() = Vector4f(this.z, this.z, this.z, this.x)
val Vector3f.zzzy get() = Vector4f(this.z, this.z, this.z, this.y)
val Vector3f.zzzz get() = Vector4f(this.z, this.z, this.z, this.z)

// ===================================== RGB =====================================
var Vector3f.r: Float get() = this.x; set(it) { this.x = it }
var Vector3f.g: Float get() = this.y; set(it) { this.y = it }
var Vector3f.b: Float get() = this.z; set(it) { this.z = it }

val Vector3f.rr get() = Vector2f(this.x, this.x)
var Vector3f.rg get() = Vector2f(this.x, this.y); set(it) { this.x = it.r; this.y = it.g }
var Vector3f.rb get() = Vector2f(this.x, this.z); set(it) { this.x = it.r; this.z = it.g }
var Vector3f.gr get() = Vector2f(this.y, this.x); set(it) { this.y = it.r; this.x = it.g }
val Vector3f.gg get() = Vector2f(this.y, this.y)
var Vector3f.gb get() = Vector2f(this.y, this.z); set(it) { this.y = it.r; this.z = it.g }
var Vector3f.br get() = Vector2f(this.z, this.x); set(it) { this.z = it.r; this.x = it.g }
var Vector3f.bg get() = Vector2f(this.z, this.y); set(it) { this.z = it.r; this.y = it.g }
val Vector3f.bb get() = Vector2f(this.z, this.z)

val Vector3f.rrr get() = Vector3f(this.x, this.x, this.x)
val Vector3f.rrg get() = Vector3f(this.x, this.x, this.y)
val Vector3f.rrb get() = Vector3f(this.x, this.x, this.z)
val Vector3f.rgr get() = Vector3f(this.x, this.y, this.x)
val Vector3f.rgg get() = Vector3f(this.x, this.y, this.y)
var Vector3f.rgb get() = Vector3f(this.x, this.y, this.z); set(it) { this.x = it.r; this.y = it.g; this.z = it.b }
val Vector3f.rbr get() = Vector3f(this.x, this.z, this.x)
var Vector3f.rbg get() = Vector3f(this.x, this.z, this.y); set(it) { this.x = it.r; this.z = it.g; this.y = it.b }
val Vector3f.rbb get() = Vector3f(this.x, this.z, this.z)
val Vector3f.grr get() = Vector3f(this.y, this.x, this.x)
val Vector3f.grg get() = Vector3f(this.y, this.x, this.y)
var Vector3f.grb get() = Vector3f(this.y, this.x, this.z); set(it) { this.y = it.r; this.x = it.g; this.z = it.b }
val Vector3f.ggr get() = Vector3f(this.y, this.y, this.x)
val Vector3f.ggg get() = Vector3f(this.y, this.y, this.y)
val Vector3f.ggb get() = Vector3f(this.y, this.y, this.z)
var Vector3f.gbr get() = Vector3f(this.y, this.z, this.x); set(it) { this.y = it.r; this.z = it.g; this.x = it.b }
val Vector3f.gbg get() = Vector3f(this.y, this.z, this.y)
val Vector3f.gbb get() = Vector3f(this.y, this.z, this.z)
val Vector3f.brr get() = Vector3f(this.z, this.x, this.x)
var Vector3f.brg get() = Vector3f(this.z, this.x, this.y); set(it) { this.z = it.r; this.x = it.g; this.y = it.b }
val Vector3f.brb get() = Vector3f(this.z, this.x, this.z)
var Vector3f.bgr get() = Vector3f(this.z, this.y, this.x); set(it) { this.z = it.r; this.y = it.g; this.x = it.b }
val Vector3f.bgg get() = Vector3f(this.z, this.y, this.y)
val Vector3f.bgb get() = Vector3f(this.z, this.y, this.z)
val Vector3f.bbr get() = Vector3f(this.z, this.z, this.x)
val Vector3f.bbg get() = Vector3f(this.z, this.z, this.y)
val Vector3f.bbb get() = Vector3f(this.z, this.z, this.z)

val Vector3f.rrrr get() = Vector4f(this.x, this.x, this.x, this.x)
val Vector3f.rrrg get() = Vector4f(this.x, this.x, this.x, this.y)
val Vector3f.rrrb get() = Vector4f(this.x, this.x, this.x, this.z)
val Vector3f.rrgr get() = Vector4f(this.x, this.x, this.y, this.x)
val Vector3f.rrgg get() = Vector4f(this.x, this.x, this.y, this.y)
val Vector3f.rrgb get() = Vector4f(this.x, this.x, this.y, this.z)
val Vector3f.rrbr get() = Vector4f(this.x, this.x, this.z, this.x)
val Vector3f.rrbg get() = Vector4f(this.x, this.x, this.z, this.y)
val Vector3f.rrbb get() = Vector4f(this.x, this.x, this.z, this.z)
val Vector3f.rgrr get() = Vector4f(this.x, this.y, this.x, this.x)
val Vector3f.rgrg get() = Vector4f(this.x, this.y, this.x, this.y)
val Vector3f.rgrb get() = Vector4f(this.x, this.y, this.x, this.z)
val Vector3f.rggr get() = Vector4f(this.x, this.y, this.y, this.x)
val Vector3f.rggg get() = Vector4f(this.x, this.y, this.y, this.y)
val Vector3f.rggb get() = Vector4f(this.x, this.y, this.y, this.z)
val Vector3f.rgbr get() = Vector4f(this.x, this.y, this.z, this.x)
val Vector3f.rgbg get() = Vector4f(this.x, this.y, this.z, this.y)
val Vector3f.rgbb get() = Vector4f(this.x, this.y, this.z, this.z)
val Vector3f.rbrr get() = Vector4f(this.x, this.z, this.x, this.x)
val Vector3f.rbrg get() = Vector4f(this.x, this.z, this.x, this.y)
val Vector3f.rbrb get() = Vector4f(this.x, this.z, this.x, this.z)
val Vector3f.rbgr get() = Vector4f(this.x, this.z, this.y, this.x)
val Vector3f.rbgg get() = Vector4f(this.x, this.z, this.y, this.y)
val Vector3f.rbgb get() = Vector4f(this.x, this.z, this.y, this.z)
val Vector3f.rbbr get() = Vector4f(this.x, this.z, this.z, this.x)
val Vector3f.rbbg get() = Vector4f(this.x, this.z, this.z, this.y)
val Vector3f.rbbb get() = Vector4f(this.x, this.z, this.z, this.z)
val Vector3f.grrr get() = Vector4f(this.y, this.x, this.x, this.x)
val Vector3f.grrg get() = Vector4f(this.y, this.x, this.x, this.y)
val Vector3f.grrb get() = Vector4f(this.y, this.x, this.x, this.z)
val Vector3f.grgr get() = Vector4f(this.y, this.x, this.y, this.x)
val Vector3f.grgg get() = Vector4f(this.y, this.x, this.y, this.y)
val Vector3f.grgb get() = Vector4f(this.y, this.x, this.y, this.z)
val Vector3f.grbr get() = Vector4f(this.y, this.x, this.z, this.x)
val Vector3f.grbg get() = Vector4f(this.y, this.x, this.z, this.y)
val Vector3f.grbb get() = Vector4f(this.y, this.x, this.z, this.z)
val Vector3f.ggrr get() = Vector4f(this.y, this.y, this.x, this.x)
val Vector3f.ggrg get() = Vector4f(this.y, this.y, this.x, this.y)
val Vector3f.ggrb get() = Vector4f(this.y, this.y, this.x, this.z)
val Vector3f.gggr get() = Vector4f(this.y, this.y, this.y, this.x)
val Vector3f.gggg get() = Vector4f(this.y, this.y, this.y, this.y)
val Vector3f.gggb get() = Vector4f(this.y, this.y, this.y, this.z)
val Vector3f.ggbr get() = Vector4f(this.y, this.y, this.z, this.x)
val Vector3f.ggbg get() = Vector4f(this.y, this.y, this.z, this.y)
val Vector3f.ggbb get() = Vector4f(this.y, this.y, this.z, this.z)
val Vector3f.gbrr get() = Vector4f(this.y, this.z, this.x, this.x)
val Vector3f.gbrg get() = Vector4f(this.y, this.z, this.x, this.y)
val Vector3f.gbrb get() = Vector4f(this.y, this.z, this.x, this.z)
val Vector3f.gbgr get() = Vector4f(this.y, this.z, this.y, this.x)
val Vector3f.gbgg get() = Vector4f(this.y, this.z, this.y, this.y)
val Vector3f.gbgb get() = Vector4f(this.y, this.z, this.y, this.z)
val Vector3f.gbbr get() = Vector4f(this.y, this.z, this.z, this.x)
val Vector3f.gbbg get() = Vector4f(this.y, this.z, this.z, this.y)
val Vector3f.gbbb get() = Vector4f(this.y, this.z, this.z, this.z)
val Vector3f.brrr get() = Vector4f(this.z, this.x, this.x, this.x)
val Vector3f.brrg get() = Vector4f(this.z, this.x, this.x, this.y)
val Vector3f.brrb get() = Vector4f(this.z, this.x, this.x, this.z)
val Vector3f.brgr get() = Vector4f(this.z, this.x, this.y, this.x)
val Vector3f.brgg get() = Vector4f(this.z, this.x, this.y, this.y)
val Vector3f.brgb get() = Vector4f(this.z, this.x, this.y, this.z)
val Vector3f.brbr get() = Vector4f(this.z, this.x, this.z, this.x)
val Vector3f.brbg get() = Vector4f(this.z, this.x, this.z, this.y)
val Vector3f.brbb get() = Vector4f(this.z, this.x, this.z, this.z)
val Vector3f.bgrr get() = Vector4f(this.z, this.y, this.x, this.x)
val Vector3f.bgrg get() = Vector4f(this.z, this.y, this.x, this.y)
val Vector3f.bgrb get() = Vector4f(this.z, this.y, this.x, this.z)
val Vector3f.bggr get() = Vector4f(this.z, this.y, this.y, this.x)
val Vector3f.bggg get() = Vector4f(this.z, this.y, this.y, this.y)
val Vector3f.bggb get() = Vector4f(this.z, this.y, this.y, this.z)
val Vector3f.bgbr get() = Vector4f(this.z, this.y, this.z, this.x)
val Vector3f.bgbg get() = Vector4f(this.z, this.y, this.z, this.y)
val Vector3f.bgbb get() = Vector4f(this.z, this.y, this.z, this.z)
val Vector3f.bbrr get() = Vector4f(this.z, this.z, this.x, this.x)
val Vector3f.bbrg get() = Vector4f(this.z, this.z, this.x, this.y)
val Vector3f.bbrb get() = Vector4f(this.z, this.z, this.x, this.z)
val Vector3f.bbgr get() = Vector4f(this.z, this.z, this.y, this.x)
val Vector3f.bbgg get() = Vector4f(this.z, this.z, this.y, this.y)
val Vector3f.bbgb get() = Vector4f(this.z, this.z, this.y, this.z)
val Vector3f.bbbr get() = Vector4f(this.z, this.z, this.z, this.x)
val Vector3f.bbbg get() = Vector4f(this.z, this.z, this.z, this.y)
val Vector3f.bbbb get() = Vector4f(this.z, this.z, this.z, this.z)