@file:Suppress("unused", "SpellCheckingInspection")
package com.losi.create.utility.joml

import com.losi.create.math.*

fun Vector3b.toTriple() = Triple(this.x, this.y, this.z)
fun Triple<Boolean, Boolean, Boolean>.toVector() = Vector3b(this.first, this.second, this.third)

// ===================================== XYZ =====================================
val Vector3b.xx get() = Vector2b(this.x, this.x)
var Vector3b.xy get() = Vector2b(this.x, this.y); set(v) { this.x = v.x; this.y = v.y }
var Vector3b.xz get() = Vector2b(this.x, this.z); set(v) { this.x = v.x; this.z = v.y }
var Vector3b.yx get() = Vector2b(this.y, this.x); set(v) { this.y = v.x; this.x = v.y }
val Vector3b.yy get() = Vector2b(this.y, this.y)
var Vector3b.yz get() = Vector2b(this.y, this.z); set(v) { this.y = v.x; this.z = v.y }
var Vector3b.zx get() = Vector2b(this.z, this.x); set(v) { this.z = v.x; this.x = v.y }
var Vector3b.zy get() = Vector2b(this.z, this.y); set(v) { this.z = v.x; this.y = v.y }
val Vector3b.zz get() = Vector2b(this.z, this.z)

val Vector3b.xxx get() = Vector3b(this.x, this.x, this.x)
val Vector3b.xxy get() = Vector3b(this.x, this.x, this.y)
val Vector3b.xxz get() = Vector3b(this.x, this.x, this.z)
val Vector3b.xyx get() = Vector3b(this.x, this.y, this.x)
val Vector3b.xyy get() = Vector3b(this.x, this.y, this.y)
var Vector3b.xyz get() = Vector3b(this.x, this.y, this.z); set(v) { this.x = v.x; this.y = v.y; this.z = v.z }
val Vector3b.xzx get() = Vector3b(this.x, this.z, this.x)
var Vector3b.xzy get() = Vector3b(this.x, this.z, this.y); set(v) { this.x = v.x; this.z = v.y; this.y = v.z }
val Vector3b.xzz get() = Vector3b(this.x, this.z, this.z)
val Vector3b.yxx get() = Vector3b(this.y, this.x, this.x)
val Vector3b.yxy get() = Vector3b(this.y, this.x, this.y)
var Vector3b.yxz get() = Vector3b(this.y, this.x, this.z); set(v) { this.y = v.x; this.x = v.y; this.z = v.z }
val Vector3b.yyx get() = Vector3b(this.y, this.y, this.x)
val Vector3b.yyy get() = Vector3b(this.y, this.y, this.y)
val Vector3b.yyz get() = Vector3b(this.y, this.y, this.z)
var Vector3b.yzx get() = Vector3b(this.y, this.z, this.x); set(v) { this.y = v.x; this.z = v.y; this.x = v.z }
val Vector3b.yzy get() = Vector3b(this.y, this.z, this.y)
val Vector3b.yzz get() = Vector3b(this.y, this.z, this.z)
val Vector3b.zxx get() = Vector3b(this.z, this.x, this.x)
var Vector3b.zxy get() = Vector3b(this.z, this.x, this.y); set(v) { this.z = v.x; this.x = v.y; this.y = v.z }
val Vector3b.zxz get() = Vector3b(this.z, this.x, this.z)
var Vector3b.zyx get() = Vector3b(this.z, this.y, this.x); set(v) { this.z = v.x; this.y = v.y; this.x = v.z }
val Vector3b.zyy get() = Vector3b(this.z, this.y, this.y)
val Vector3b.zyz get() = Vector3b(this.z, this.y, this.z)
val Vector3b.zzx get() = Vector3b(this.z, this.z, this.x)
val Vector3b.zzy get() = Vector3b(this.z, this.z, this.y)
val Vector3b.zzz get() = Vector3b(this.z, this.z, this.z)

val Vector3b.xxxx get() = Vector4b(this.x, this.x, this.x, this.x)
val Vector3b.xxxy get() = Vector4b(this.x, this.x, this.x, this.y)
val Vector3b.xxxz get() = Vector4b(this.x, this.x, this.x, this.z)
val Vector3b.xxyx get() = Vector4b(this.x, this.x, this.y, this.x)
val Vector3b.xxyy get() = Vector4b(this.x, this.x, this.y, this.y)
val Vector3b.xxyz get() = Vector4b(this.x, this.x, this.y, this.z)
val Vector3b.xxzx get() = Vector4b(this.x, this.x, this.z, this.x)
val Vector3b.xxzy get() = Vector4b(this.x, this.x, this.z, this.y)
val Vector3b.xxzz get() = Vector4b(this.x, this.x, this.z, this.z)
val Vector3b.xyxx get() = Vector4b(this.x, this.y, this.x, this.x)
val Vector3b.xyxy get() = Vector4b(this.x, this.y, this.x, this.y)
val Vector3b.xyxz get() = Vector4b(this.x, this.y, this.x, this.z)
val Vector3b.xyyx get() = Vector4b(this.x, this.y, this.y, this.x)
val Vector3b.xyyy get() = Vector4b(this.x, this.y, this.y, this.y)
val Vector3b.xyyz get() = Vector4b(this.x, this.y, this.y, this.z)
val Vector3b.xyzx get() = Vector4b(this.x, this.y, this.z, this.x)
val Vector3b.xyzy get() = Vector4b(this.x, this.y, this.z, this.y)
val Vector3b.xyzz get() = Vector4b(this.x, this.y, this.z, this.z)
val Vector3b.xzxx get() = Vector4b(this.x, this.z, this.x, this.x)
val Vector3b.xzxy get() = Vector4b(this.x, this.z, this.x, this.y)
val Vector3b.xzxz get() = Vector4b(this.x, this.z, this.x, this.z)
val Vector3b.xzyx get() = Vector4b(this.x, this.z, this.y, this.x)
val Vector3b.xzyy get() = Vector4b(this.x, this.z, this.y, this.y)
val Vector3b.xzyz get() = Vector4b(this.x, this.z, this.y, this.z)
val Vector3b.xzzx get() = Vector4b(this.x, this.z, this.z, this.x)
val Vector3b.xzzy get() = Vector4b(this.x, this.z, this.z, this.y)
val Vector3b.xzzz get() = Vector4b(this.x, this.z, this.z, this.z)
val Vector3b.yxxx get() = Vector4b(this.y, this.x, this.x, this.x)
val Vector3b.yxxy get() = Vector4b(this.y, this.x, this.x, this.y)
val Vector3b.yxxz get() = Vector4b(this.y, this.x, this.x, this.z)
val Vector3b.yxyx get() = Vector4b(this.y, this.x, this.y, this.x)
val Vector3b.yxyy get() = Vector4b(this.y, this.x, this.y, this.y)
val Vector3b.yxyz get() = Vector4b(this.y, this.x, this.y, this.z)
val Vector3b.yxzx get() = Vector4b(this.y, this.x, this.z, this.x)
val Vector3b.yxzy get() = Vector4b(this.y, this.x, this.z, this.y)
val Vector3b.yxzz get() = Vector4b(this.y, this.x, this.z, this.z)
val Vector3b.yyxx get() = Vector4b(this.y, this.y, this.x, this.x)
val Vector3b.yyxy get() = Vector4b(this.y, this.y, this.x, this.y)
val Vector3b.yyxz get() = Vector4b(this.y, this.y, this.x, this.z)
val Vector3b.yyyx get() = Vector4b(this.y, this.y, this.y, this.x)
val Vector3b.yyyy get() = Vector4b(this.y, this.y, this.y, this.y)
val Vector3b.yyyz get() = Vector4b(this.y, this.y, this.y, this.z)
val Vector3b.yyzx get() = Vector4b(this.y, this.y, this.z, this.x)
val Vector3b.yyzy get() = Vector4b(this.y, this.y, this.z, this.y)
val Vector3b.yyzz get() = Vector4b(this.y, this.y, this.z, this.z)
val Vector3b.yzxx get() = Vector4b(this.y, this.z, this.x, this.x)
val Vector3b.yzxy get() = Vector4b(this.y, this.z, this.x, this.y)
val Vector3b.yzxz get() = Vector4b(this.y, this.z, this.x, this.z)
val Vector3b.yzyx get() = Vector4b(this.y, this.z, this.y, this.x)
val Vector3b.yzyy get() = Vector4b(this.y, this.z, this.y, this.y)
val Vector3b.yzyz get() = Vector4b(this.y, this.z, this.y, this.z)
val Vector3b.yzzx get() = Vector4b(this.y, this.z, this.z, this.x)
val Vector3b.yzzy get() = Vector4b(this.y, this.z, this.z, this.y)
val Vector3b.yzzz get() = Vector4b(this.y, this.z, this.z, this.z)
val Vector3b.zxxx get() = Vector4b(this.z, this.x, this.x, this.x)
val Vector3b.zxxy get() = Vector4b(this.z, this.x, this.x, this.y)
val Vector3b.zxxz get() = Vector4b(this.z, this.x, this.x, this.z)
val Vector3b.zxyx get() = Vector4b(this.z, this.x, this.y, this.x)
val Vector3b.zxyy get() = Vector4b(this.z, this.x, this.y, this.y)
val Vector3b.zxyz get() = Vector4b(this.z, this.x, this.y, this.z)
val Vector3b.zxzx get() = Vector4b(this.z, this.x, this.z, this.x)
val Vector3b.zxzy get() = Vector4b(this.z, this.x, this.z, this.y)
val Vector3b.zxzz get() = Vector4b(this.z, this.x, this.z, this.z)
val Vector3b.zyxx get() = Vector4b(this.z, this.y, this.x, this.x)
val Vector3b.zyxy get() = Vector4b(this.z, this.y, this.x, this.y)
val Vector3b.zyxz get() = Vector4b(this.z, this.y, this.x, this.z)
val Vector3b.zyyx get() = Vector4b(this.z, this.y, this.y, this.x)
val Vector3b.zyyy get() = Vector4b(this.z, this.y, this.y, this.y)
val Vector3b.zyyz get() = Vector4b(this.z, this.y, this.y, this.z)
val Vector3b.zyzx get() = Vector4b(this.z, this.y, this.z, this.x)
val Vector3b.zyzy get() = Vector4b(this.z, this.y, this.z, this.y)
val Vector3b.zyzz get() = Vector4b(this.z, this.y, this.z, this.z)
val Vector3b.zzxx get() = Vector4b(this.z, this.z, this.x, this.x)
val Vector3b.zzxy get() = Vector4b(this.z, this.z, this.x, this.y)
val Vector3b.zzxz get() = Vector4b(this.z, this.z, this.x, this.z)
val Vector3b.zzyx get() = Vector4b(this.z, this.z, this.y, this.x)
val Vector3b.zzyy get() = Vector4b(this.z, this.z, this.y, this.y)
val Vector3b.zzyz get() = Vector4b(this.z, this.z, this.y, this.z)
val Vector3b.zzzx get() = Vector4b(this.z, this.z, this.z, this.x)
val Vector3b.zzzy get() = Vector4b(this.z, this.z, this.z, this.y)
val Vector3b.zzzz get() = Vector4b(this.z, this.z, this.z, this.z)

// ===================================== RGB =====================================
var Vector3b.r: Boolean get() = this.x; set(it) { this.x = it }
var Vector3b.g: Boolean get() = this.y; set(it) { this.y = it }
var Vector3b.b: Boolean get() = this.z; set(it) { this.z = it }

val Vector3b.rr get() = Vector2b(this.x, this.x)
var Vector3b.rg get() = Vector2b(this.x, this.y); set(v) { this.x = v.x; this.y = v.y }
var Vector3b.rb get() = Vector2b(this.x, this.z); set(v) { this.x = v.x; this.z = v.y }
var Vector3b.gr get() = Vector2b(this.y, this.x); set(v) { this.y = v.x; this.x = v.y }
val Vector3b.gg get() = Vector2b(this.y, this.y)
var Vector3b.gb get() = Vector2b(this.y, this.z); set(v) { this.y = v.x; this.z = v.y }
var Vector3b.br get() = Vector2b(this.z, this.x); set(v) { this.z = v.x; this.x = v.y }
var Vector3b.bg get() = Vector2b(this.z, this.y); set(v) { this.z = v.x; this.y = v.y }
val Vector3b.bb get() = Vector2b(this.z, this.z)

val Vector3b.rrr get() = Vector3b(this.x, this.x, this.x)
val Vector3b.rrg get() = Vector3b(this.x, this.x, this.y)
val Vector3b.rrb get() = Vector3b(this.x, this.x, this.z)
val Vector3b.rgr get() = Vector3b(this.x, this.y, this.x)
val Vector3b.rgg get() = Vector3b(this.x, this.y, this.y)
var Vector3b.rgb get() = Vector3b(this.x, this.y, this.z); set(v) { this.x = v.x; this.y = v.y; this.z = v.z }
val Vector3b.rbr get() = Vector3b(this.x, this.z, this.x)
var Vector3b.rbg get() = Vector3b(this.x, this.z, this.y); set(v) { this.x = v.x; this.z = v.y; this.y = v.z }
val Vector3b.rbb get() = Vector3b(this.x, this.z, this.z)
val Vector3b.grr get() = Vector3b(this.y, this.x, this.x)
val Vector3b.grg get() = Vector3b(this.y, this.x, this.y)
var Vector3b.grb get() = Vector3b(this.y, this.x, this.z); set(v) { this.y = v.x; this.x = v.y; this.z = v.z }
val Vector3b.ggr get() = Vector3b(this.y, this.y, this.x)
val Vector3b.ggg get() = Vector3b(this.y, this.y, this.y)
val Vector3b.ggb get() = Vector3b(this.y, this.y, this.z)
var Vector3b.gbr get() = Vector3b(this.y, this.z, this.x); set(v) { this.y = v.x; this.z = v.y; this.x = v.z }
val Vector3b.gbg get() = Vector3b(this.y, this.z, this.y)
val Vector3b.gbb get() = Vector3b(this.y, this.z, this.z)
val Vector3b.brr get() = Vector3b(this.z, this.x, this.x)
var Vector3b.brg get() = Vector3b(this.z, this.x, this.y); set(v) { this.z = v.x; this.x = v.y; this.y = v.z }
val Vector3b.brb get() = Vector3b(this.z, this.x, this.z)
var Vector3b.bgr get() = Vector3b(this.z, this.y, this.x); set(v) { this.z = v.x; this.y = v.y; this.x = v.z }
val Vector3b.bgg get() = Vector3b(this.z, this.y, this.y)
val Vector3b.bgb get() = Vector3b(this.z, this.y, this.z)
val Vector3b.bbr get() = Vector3b(this.z, this.z, this.x)
val Vector3b.bbg get() = Vector3b(this.z, this.z, this.y)
val Vector3b.bbb get() = Vector3b(this.z, this.z, this.z)

val Vector3b.rrrr get() = Vector4b(this.x, this.x, this.x, this.x)
val Vector3b.rrrg get() = Vector4b(this.x, this.x, this.x, this.y)
val Vector3b.rrrb get() = Vector4b(this.x, this.x, this.x, this.z)
val Vector3b.rrgr get() = Vector4b(this.x, this.x, this.y, this.x)
val Vector3b.rrgg get() = Vector4b(this.x, this.x, this.y, this.y)
val Vector3b.rrgb get() = Vector4b(this.x, this.x, this.y, this.z)
val Vector3b.rrbr get() = Vector4b(this.x, this.x, this.z, this.x)
val Vector3b.rrbg get() = Vector4b(this.x, this.x, this.z, this.y)
val Vector3b.rrbb get() = Vector4b(this.x, this.x, this.z, this.z)
val Vector3b.rgrr get() = Vector4b(this.x, this.y, this.x, this.x)
val Vector3b.rgrg get() = Vector4b(this.x, this.y, this.x, this.y)
val Vector3b.rgrb get() = Vector4b(this.x, this.y, this.x, this.z)
val Vector3b.rggr get() = Vector4b(this.x, this.y, this.y, this.x)
val Vector3b.rggg get() = Vector4b(this.x, this.y, this.y, this.y)
val Vector3b.rggb get() = Vector4b(this.x, this.y, this.y, this.z)
val Vector3b.rgbr get() = Vector4b(this.x, this.y, this.z, this.x)
val Vector3b.rgbg get() = Vector4b(this.x, this.y, this.z, this.y)
val Vector3b.rgbb get() = Vector4b(this.x, this.y, this.z, this.z)
val Vector3b.rbrr get() = Vector4b(this.x, this.z, this.x, this.x)
val Vector3b.rbrg get() = Vector4b(this.x, this.z, this.x, this.y)
val Vector3b.rbrb get() = Vector4b(this.x, this.z, this.x, this.z)
val Vector3b.rbgr get() = Vector4b(this.x, this.z, this.y, this.x)
val Vector3b.rbgg get() = Vector4b(this.x, this.z, this.y, this.y)
val Vector3b.rbgb get() = Vector4b(this.x, this.z, this.y, this.z)
val Vector3b.rbbr get() = Vector4b(this.x, this.z, this.z, this.x)
val Vector3b.rbbg get() = Vector4b(this.x, this.z, this.z, this.y)
val Vector3b.rbbb get() = Vector4b(this.x, this.z, this.z, this.z)
val Vector3b.grrr get() = Vector4b(this.y, this.x, this.x, this.x)
val Vector3b.grrg get() = Vector4b(this.y, this.x, this.x, this.y)
val Vector3b.grrb get() = Vector4b(this.y, this.x, this.x, this.z)
val Vector3b.grgr get() = Vector4b(this.y, this.x, this.y, this.x)
val Vector3b.grgg get() = Vector4b(this.y, this.x, this.y, this.y)
val Vector3b.grgb get() = Vector4b(this.y, this.x, this.y, this.z)
val Vector3b.grbr get() = Vector4b(this.y, this.x, this.z, this.x)
val Vector3b.grbg get() = Vector4b(this.y, this.x, this.z, this.y)
val Vector3b.grbb get() = Vector4b(this.y, this.x, this.z, this.z)
val Vector3b.ggrr get() = Vector4b(this.y, this.y, this.x, this.x)
val Vector3b.ggrg get() = Vector4b(this.y, this.y, this.x, this.y)
val Vector3b.ggrb get() = Vector4b(this.y, this.y, this.x, this.z)
val Vector3b.gggr get() = Vector4b(this.y, this.y, this.y, this.x)
val Vector3b.gggg get() = Vector4b(this.y, this.y, this.y, this.y)
val Vector3b.gggb get() = Vector4b(this.y, this.y, this.y, this.z)
val Vector3b.ggbr get() = Vector4b(this.y, this.y, this.z, this.x)
val Vector3b.ggbg get() = Vector4b(this.y, this.y, this.z, this.y)
val Vector3b.ggbb get() = Vector4b(this.y, this.y, this.z, this.z)
val Vector3b.gbrr get() = Vector4b(this.y, this.z, this.x, this.x)
val Vector3b.gbrg get() = Vector4b(this.y, this.z, this.x, this.y)
val Vector3b.gbrb get() = Vector4b(this.y, this.z, this.x, this.z)
val Vector3b.gbgr get() = Vector4b(this.y, this.z, this.y, this.x)
val Vector3b.gbgg get() = Vector4b(this.y, this.z, this.y, this.y)
val Vector3b.gbgb get() = Vector4b(this.y, this.z, this.y, this.z)
val Vector3b.gbbr get() = Vector4b(this.y, this.z, this.z, this.x)
val Vector3b.gbbg get() = Vector4b(this.y, this.z, this.z, this.y)
val Vector3b.gbbb get() = Vector4b(this.y, this.z, this.z, this.z)
val Vector3b.brrr get() = Vector4b(this.z, this.x, this.x, this.x)
val Vector3b.brrg get() = Vector4b(this.z, this.x, this.x, this.y)
val Vector3b.brrb get() = Vector4b(this.z, this.x, this.x, this.z)
val Vector3b.brgr get() = Vector4b(this.z, this.x, this.y, this.x)
val Vector3b.brgg get() = Vector4b(this.z, this.x, this.y, this.y)
val Vector3b.brgb get() = Vector4b(this.z, this.x, this.y, this.z)
val Vector3b.brbr get() = Vector4b(this.z, this.x, this.z, this.x)
val Vector3b.brbg get() = Vector4b(this.z, this.x, this.z, this.y)
val Vector3b.brbb get() = Vector4b(this.z, this.x, this.z, this.z)
val Vector3b.bgrr get() = Vector4b(this.z, this.y, this.x, this.x)
val Vector3b.bgrg get() = Vector4b(this.z, this.y, this.x, this.y)
val Vector3b.bgrb get() = Vector4b(this.z, this.y, this.x, this.z)
val Vector3b.bggr get() = Vector4b(this.z, this.y, this.y, this.x)
val Vector3b.bggg get() = Vector4b(this.z, this.y, this.y, this.y)
val Vector3b.bggb get() = Vector4b(this.z, this.y, this.y, this.z)
val Vector3b.bgbr get() = Vector4b(this.z, this.y, this.z, this.x)
val Vector3b.bgbg get() = Vector4b(this.z, this.y, this.z, this.y)
val Vector3b.bgbb get() = Vector4b(this.z, this.y, this.z, this.z)
val Vector3b.bbrr get() = Vector4b(this.z, this.z, this.x, this.x)
val Vector3b.bbrg get() = Vector4b(this.z, this.z, this.x, this.y)
val Vector3b.bbrb get() = Vector4b(this.z, this.z, this.x, this.z)
val Vector3b.bbgr get() = Vector4b(this.z, this.z, this.y, this.x)
val Vector3b.bbgg get() = Vector4b(this.z, this.z, this.y, this.y)
val Vector3b.bbgb get() = Vector4b(this.z, this.z, this.y, this.z)
val Vector3b.bbbr get() = Vector4b(this.z, this.z, this.z, this.x)
val Vector3b.bbbg get() = Vector4b(this.z, this.z, this.z, this.y)
val Vector3b.bbbb get() = Vector4b(this.z, this.z, this.z, this.z)