@file:Suppress("unused", "SpellCheckingInspection")
package com.losi.create.utility.joml

import org.joml.*

fun Vector3i.toTriple() = Triple(this.x, this.y, this.z)
fun Triple<Int, Int, Int>.toVector() = Vector3i(this.first, this.second, this.third)

// ===================================== XYZ =====================================
val Vector3i.xx get() = Vector2i(this.x, this.x)
var Vector3i.xy get() = Vector2i(this.x, this.y); set(v) { this.x = v.x; this.y = v.y }
var Vector3i.xz get() = Vector2i(this.x, this.z); set(v) { this.x = v.x; this.z = v.y }
var Vector3i.yx get() = Vector2i(this.y, this.x); set(v) { this.y = v.x; this.x = v.y }
val Vector3i.yy get() = Vector2i(this.y, this.y)
var Vector3i.yz get() = Vector2i(this.y, this.z); set(v) { this.y = v.x; this.z = v.y }
var Vector3i.zx get() = Vector2i(this.z, this.x); set(v) { this.z = v.x; this.x = v.y }
var Vector3i.zy get() = Vector2i(this.z, this.y); set(v) { this.z = v.x; this.y = v.y }
val Vector3i.zz get() = Vector2i(this.z, this.z)

val Vector3i.xxx get() = Vector3i(this.x, this.x, this.x)
val Vector3i.xxy get() = Vector3i(this.x, this.x, this.y)
val Vector3i.xxz get() = Vector3i(this.x, this.x, this.z)
val Vector3i.xyx get() = Vector3i(this.x, this.y, this.x)
val Vector3i.xyy get() = Vector3i(this.x, this.y, this.y)
var Vector3i.xyz get() = Vector3i(this.x, this.y, this.z); set(v) { this.x = v.x; this.y = v.y; this.z = v.z }
val Vector3i.xzx get() = Vector3i(this.x, this.z, this.x)
var Vector3i.xzy get() = Vector3i(this.x, this.z, this.y); set(v) { this.x = v.x; this.z = v.y; this.y = v.z }
val Vector3i.xzz get() = Vector3i(this.x, this.z, this.z)
val Vector3i.yxx get() = Vector3i(this.y, this.x, this.x)
val Vector3i.yxy get() = Vector3i(this.y, this.x, this.y)
var Vector3i.yxz get() = Vector3i(this.y, this.x, this.z); set(v) { this.y = v.x; this.x = v.y; this.z = v.z }
val Vector3i.yyx get() = Vector3i(this.y, this.y, this.x)
val Vector3i.yyy get() = Vector3i(this.y, this.y, this.y)
val Vector3i.yyz get() = Vector3i(this.y, this.y, this.z)
var Vector3i.yzx get() = Vector3i(this.y, this.z, this.x); set(v) { this.y = v.x; this.z = v.y; this.x = v.z }
val Vector3i.yzy get() = Vector3i(this.y, this.z, this.y)
val Vector3i.yzz get() = Vector3i(this.y, this.z, this.z)
val Vector3i.zxx get() = Vector3i(this.z, this.x, this.x)
var Vector3i.zxy get() = Vector3i(this.z, this.x, this.y); set(v) { this.z = v.x; this.x = v.y; this.y = v.z }
val Vector3i.zxz get() = Vector3i(this.z, this.x, this.z)
var Vector3i.zyx get() = Vector3i(this.z, this.y, this.x); set(v) { this.z = v.x; this.y = v.y; this.x = v.z }
val Vector3i.zyy get() = Vector3i(this.z, this.y, this.y)
val Vector3i.zyz get() = Vector3i(this.z, this.y, this.z)
val Vector3i.zzx get() = Vector3i(this.z, this.z, this.x)
val Vector3i.zzy get() = Vector3i(this.z, this.z, this.y)
val Vector3i.zzz get() = Vector3i(this.z, this.z, this.z)

val Vector3i.xxxx get() = Vector4i(this.x, this.x, this.x, this.x)
val Vector3i.xxxy get() = Vector4i(this.x, this.x, this.x, this.y)
val Vector3i.xxxz get() = Vector4i(this.x, this.x, this.x, this.z)
val Vector3i.xxyx get() = Vector4i(this.x, this.x, this.y, this.x)
val Vector3i.xxyy get() = Vector4i(this.x, this.x, this.y, this.y)
val Vector3i.xxyz get() = Vector4i(this.x, this.x, this.y, this.z)
val Vector3i.xxzx get() = Vector4i(this.x, this.x, this.z, this.x)
val Vector3i.xxzy get() = Vector4i(this.x, this.x, this.z, this.y)
val Vector3i.xxzz get() = Vector4i(this.x, this.x, this.z, this.z)
val Vector3i.xyxx get() = Vector4i(this.x, this.y, this.x, this.x)
val Vector3i.xyxy get() = Vector4i(this.x, this.y, this.x, this.y)
val Vector3i.xyxz get() = Vector4i(this.x, this.y, this.x, this.z)
val Vector3i.xyyx get() = Vector4i(this.x, this.y, this.y, this.x)
val Vector3i.xyyy get() = Vector4i(this.x, this.y, this.y, this.y)
val Vector3i.xyyz get() = Vector4i(this.x, this.y, this.y, this.z)
val Vector3i.xyzx get() = Vector4i(this.x, this.y, this.z, this.x)
val Vector3i.xyzy get() = Vector4i(this.x, this.y, this.z, this.y)
val Vector3i.xyzz get() = Vector4i(this.x, this.y, this.z, this.z)
val Vector3i.xzxx get() = Vector4i(this.x, this.z, this.x, this.x)
val Vector3i.xzxy get() = Vector4i(this.x, this.z, this.x, this.y)
val Vector3i.xzxz get() = Vector4i(this.x, this.z, this.x, this.z)
val Vector3i.xzyx get() = Vector4i(this.x, this.z, this.y, this.x)
val Vector3i.xzyy get() = Vector4i(this.x, this.z, this.y, this.y)
val Vector3i.xzyz get() = Vector4i(this.x, this.z, this.y, this.z)
val Vector3i.xzzx get() = Vector4i(this.x, this.z, this.z, this.x)
val Vector3i.xzzy get() = Vector4i(this.x, this.z, this.z, this.y)
val Vector3i.xzzz get() = Vector4i(this.x, this.z, this.z, this.z)
val Vector3i.yxxx get() = Vector4i(this.y, this.x, this.x, this.x)
val Vector3i.yxxy get() = Vector4i(this.y, this.x, this.x, this.y)
val Vector3i.yxxz get() = Vector4i(this.y, this.x, this.x, this.z)
val Vector3i.yxyx get() = Vector4i(this.y, this.x, this.y, this.x)
val Vector3i.yxyy get() = Vector4i(this.y, this.x, this.y, this.y)
val Vector3i.yxyz get() = Vector4i(this.y, this.x, this.y, this.z)
val Vector3i.yxzx get() = Vector4i(this.y, this.x, this.z, this.x)
val Vector3i.yxzy get() = Vector4i(this.y, this.x, this.z, this.y)
val Vector3i.yxzz get() = Vector4i(this.y, this.x, this.z, this.z)
val Vector3i.yyxx get() = Vector4i(this.y, this.y, this.x, this.x)
val Vector3i.yyxy get() = Vector4i(this.y, this.y, this.x, this.y)
val Vector3i.yyxz get() = Vector4i(this.y, this.y, this.x, this.z)
val Vector3i.yyyx get() = Vector4i(this.y, this.y, this.y, this.x)
val Vector3i.yyyy get() = Vector4i(this.y, this.y, this.y, this.y)
val Vector3i.yyyz get() = Vector4i(this.y, this.y, this.y, this.z)
val Vector3i.yyzx get() = Vector4i(this.y, this.y, this.z, this.x)
val Vector3i.yyzy get() = Vector4i(this.y, this.y, this.z, this.y)
val Vector3i.yyzz get() = Vector4i(this.y, this.y, this.z, this.z)
val Vector3i.yzxx get() = Vector4i(this.y, this.z, this.x, this.x)
val Vector3i.yzxy get() = Vector4i(this.y, this.z, this.x, this.y)
val Vector3i.yzxz get() = Vector4i(this.y, this.z, this.x, this.z)
val Vector3i.yzyx get() = Vector4i(this.y, this.z, this.y, this.x)
val Vector3i.yzyy get() = Vector4i(this.y, this.z, this.y, this.y)
val Vector3i.yzyz get() = Vector4i(this.y, this.z, this.y, this.z)
val Vector3i.yzzx get() = Vector4i(this.y, this.z, this.z, this.x)
val Vector3i.yzzy get() = Vector4i(this.y, this.z, this.z, this.y)
val Vector3i.yzzz get() = Vector4i(this.y, this.z, this.z, this.z)
val Vector3i.zxxx get() = Vector4i(this.z, this.x, this.x, this.x)
val Vector3i.zxxy get() = Vector4i(this.z, this.x, this.x, this.y)
val Vector3i.zxxz get() = Vector4i(this.z, this.x, this.x, this.z)
val Vector3i.zxyx get() = Vector4i(this.z, this.x, this.y, this.x)
val Vector3i.zxyy get() = Vector4i(this.z, this.x, this.y, this.y)
val Vector3i.zxyz get() = Vector4i(this.z, this.x, this.y, this.z)
val Vector3i.zxzx get() = Vector4i(this.z, this.x, this.z, this.x)
val Vector3i.zxzy get() = Vector4i(this.z, this.x, this.z, this.y)
val Vector3i.zxzz get() = Vector4i(this.z, this.x, this.z, this.z)
val Vector3i.zyxx get() = Vector4i(this.z, this.y, this.x, this.x)
val Vector3i.zyxy get() = Vector4i(this.z, this.y, this.x, this.y)
val Vector3i.zyxz get() = Vector4i(this.z, this.y, this.x, this.z)
val Vector3i.zyyx get() = Vector4i(this.z, this.y, this.y, this.x)
val Vector3i.zyyy get() = Vector4i(this.z, this.y, this.y, this.y)
val Vector3i.zyyz get() = Vector4i(this.z, this.y, this.y, this.z)
val Vector3i.zyzx get() = Vector4i(this.z, this.y, this.z, this.x)
val Vector3i.zyzy get() = Vector4i(this.z, this.y, this.z, this.y)
val Vector3i.zyzz get() = Vector4i(this.z, this.y, this.z, this.z)
val Vector3i.zzxx get() = Vector4i(this.z, this.z, this.x, this.x)
val Vector3i.zzxy get() = Vector4i(this.z, this.z, this.x, this.y)
val Vector3i.zzxz get() = Vector4i(this.z, this.z, this.x, this.z)
val Vector3i.zzyx get() = Vector4i(this.z, this.z, this.y, this.x)
val Vector3i.zzyy get() = Vector4i(this.z, this.z, this.y, this.y)
val Vector3i.zzyz get() = Vector4i(this.z, this.z, this.y, this.z)
val Vector3i.zzzx get() = Vector4i(this.z, this.z, this.z, this.x)
val Vector3i.zzzy get() = Vector4i(this.z, this.z, this.z, this.y)
val Vector3i.zzzz get() = Vector4i(this.z, this.z, this.z, this.z)

// ===================================== RGB =====================================
var Vector3i.r: Int get() = this.x; set(it) { this.x = it }
var Vector3i.g: Int get() = this.y; set(it) { this.y = it }
var Vector3i.b: Int get() = this.z; set(it) { this.z = it }

val Vector3i.rr get() = Vector2i(this.x, this.x)
var Vector3i.rg get() = Vector2i(this.x, this.y); set(v) { this.x = v.x; this.y = v.y }
var Vector3i.rb get() = Vector2i(this.x, this.z); set(v) { this.x = v.x; this.z = v.y }
var Vector3i.gr get() = Vector2i(this.y, this.x); set(v) { this.y = v.x; this.x = v.y }
val Vector3i.gg get() = Vector2i(this.y, this.y)
var Vector3i.gb get() = Vector2i(this.y, this.z); set(v) { this.y = v.x; this.z = v.y }
var Vector3i.br get() = Vector2i(this.z, this.x); set(v) { this.z = v.x; this.x = v.y }
var Vector3i.bg get() = Vector2i(this.z, this.y); set(v) { this.z = v.x; this.y = v.y }
val Vector3i.bb get() = Vector2i(this.z, this.z)

val Vector3i.rrr get() = Vector3i(this.x, this.x, this.x)
val Vector3i.rrg get() = Vector3i(this.x, this.x, this.y)
val Vector3i.rrb get() = Vector3i(this.x, this.x, this.z)
val Vector3i.rgr get() = Vector3i(this.x, this.y, this.x)
val Vector3i.rgg get() = Vector3i(this.x, this.y, this.y)
var Vector3i.rgb get() = Vector3i(this.x, this.y, this.z); set(v) { this.x = v.x; this.y = v.y; this.z = v.z }
val Vector3i.rbr get() = Vector3i(this.x, this.z, this.x)
var Vector3i.rbg get() = Vector3i(this.x, this.z, this.y); set(v) { this.x = v.x; this.z = v.y; this.y = v.z }
val Vector3i.rbb get() = Vector3i(this.x, this.z, this.z)
val Vector3i.grr get() = Vector3i(this.y, this.x, this.x)
val Vector3i.grg get() = Vector3i(this.y, this.x, this.y)
var Vector3i.grb get() = Vector3i(this.y, this.x, this.z); set(v) { this.y = v.x; this.x = v.y; this.z = v.z }
val Vector3i.ggr get() = Vector3i(this.y, this.y, this.x)
val Vector3i.ggg get() = Vector3i(this.y, this.y, this.y)
val Vector3i.ggb get() = Vector3i(this.y, this.y, this.z)
var Vector3i.gbr get() = Vector3i(this.y, this.z, this.x); set(v) { this.y = v.x; this.z = v.y; this.x = v.z }
val Vector3i.gbg get() = Vector3i(this.y, this.z, this.y)
val Vector3i.gbb get() = Vector3i(this.y, this.z, this.z)
val Vector3i.brr get() = Vector3i(this.z, this.x, this.x)
var Vector3i.brg get() = Vector3i(this.z, this.x, this.y); set(v) { this.z = v.x; this.x = v.y; this.y = v.z }
val Vector3i.brb get() = Vector3i(this.z, this.x, this.z)
var Vector3i.bgr get() = Vector3i(this.z, this.y, this.x); set(v) { this.z = v.x; this.y = v.y; this.x = v.z }
val Vector3i.bgg get() = Vector3i(this.z, this.y, this.y)
val Vector3i.bgb get() = Vector3i(this.z, this.y, this.z)
val Vector3i.bbr get() = Vector3i(this.z, this.z, this.x)
val Vector3i.bbg get() = Vector3i(this.z, this.z, this.y)
val Vector3i.bbb get() = Vector3i(this.z, this.z, this.z)

val Vector3i.rrrr get() = Vector4i(this.x, this.x, this.x, this.x)
val Vector3i.rrrg get() = Vector4i(this.x, this.x, this.x, this.y)
val Vector3i.rrrb get() = Vector4i(this.x, this.x, this.x, this.z)
val Vector3i.rrgr get() = Vector4i(this.x, this.x, this.y, this.x)
val Vector3i.rrgg get() = Vector4i(this.x, this.x, this.y, this.y)
val Vector3i.rrgb get() = Vector4i(this.x, this.x, this.y, this.z)
val Vector3i.rrbr get() = Vector4i(this.x, this.x, this.z, this.x)
val Vector3i.rrbg get() = Vector4i(this.x, this.x, this.z, this.y)
val Vector3i.rrbb get() = Vector4i(this.x, this.x, this.z, this.z)
val Vector3i.rgrr get() = Vector4i(this.x, this.y, this.x, this.x)
val Vector3i.rgrg get() = Vector4i(this.x, this.y, this.x, this.y)
val Vector3i.rgrb get() = Vector4i(this.x, this.y, this.x, this.z)
val Vector3i.rggr get() = Vector4i(this.x, this.y, this.y, this.x)
val Vector3i.rggg get() = Vector4i(this.x, this.y, this.y, this.y)
val Vector3i.rggb get() = Vector4i(this.x, this.y, this.y, this.z)
val Vector3i.rgbr get() = Vector4i(this.x, this.y, this.z, this.x)
val Vector3i.rgbg get() = Vector4i(this.x, this.y, this.z, this.y)
val Vector3i.rgbb get() = Vector4i(this.x, this.y, this.z, this.z)
val Vector3i.rbrr get() = Vector4i(this.x, this.z, this.x, this.x)
val Vector3i.rbrg get() = Vector4i(this.x, this.z, this.x, this.y)
val Vector3i.rbrb get() = Vector4i(this.x, this.z, this.x, this.z)
val Vector3i.rbgr get() = Vector4i(this.x, this.z, this.y, this.x)
val Vector3i.rbgg get() = Vector4i(this.x, this.z, this.y, this.y)
val Vector3i.rbgb get() = Vector4i(this.x, this.z, this.y, this.z)
val Vector3i.rbbr get() = Vector4i(this.x, this.z, this.z, this.x)
val Vector3i.rbbg get() = Vector4i(this.x, this.z, this.z, this.y)
val Vector3i.rbbb get() = Vector4i(this.x, this.z, this.z, this.z)
val Vector3i.grrr get() = Vector4i(this.y, this.x, this.x, this.x)
val Vector3i.grrg get() = Vector4i(this.y, this.x, this.x, this.y)
val Vector3i.grrb get() = Vector4i(this.y, this.x, this.x, this.z)
val Vector3i.grgr get() = Vector4i(this.y, this.x, this.y, this.x)
val Vector3i.grgg get() = Vector4i(this.y, this.x, this.y, this.y)
val Vector3i.grgb get() = Vector4i(this.y, this.x, this.y, this.z)
val Vector3i.grbr get() = Vector4i(this.y, this.x, this.z, this.x)
val Vector3i.grbg get() = Vector4i(this.y, this.x, this.z, this.y)
val Vector3i.grbb get() = Vector4i(this.y, this.x, this.z, this.z)
val Vector3i.ggrr get() = Vector4i(this.y, this.y, this.x, this.x)
val Vector3i.ggrg get() = Vector4i(this.y, this.y, this.x, this.y)
val Vector3i.ggrb get() = Vector4i(this.y, this.y, this.x, this.z)
val Vector3i.gggr get() = Vector4i(this.y, this.y, this.y, this.x)
val Vector3i.gggg get() = Vector4i(this.y, this.y, this.y, this.y)
val Vector3i.gggb get() = Vector4i(this.y, this.y, this.y, this.z)
val Vector3i.ggbr get() = Vector4i(this.y, this.y, this.z, this.x)
val Vector3i.ggbg get() = Vector4i(this.y, this.y, this.z, this.y)
val Vector3i.ggbb get() = Vector4i(this.y, this.y, this.z, this.z)
val Vector3i.gbrr get() = Vector4i(this.y, this.z, this.x, this.x)
val Vector3i.gbrg get() = Vector4i(this.y, this.z, this.x, this.y)
val Vector3i.gbrb get() = Vector4i(this.y, this.z, this.x, this.z)
val Vector3i.gbgr get() = Vector4i(this.y, this.z, this.y, this.x)
val Vector3i.gbgg get() = Vector4i(this.y, this.z, this.y, this.y)
val Vector3i.gbgb get() = Vector4i(this.y, this.z, this.y, this.z)
val Vector3i.gbbr get() = Vector4i(this.y, this.z, this.z, this.x)
val Vector3i.gbbg get() = Vector4i(this.y, this.z, this.z, this.y)
val Vector3i.gbbb get() = Vector4i(this.y, this.z, this.z, this.z)
val Vector3i.brrr get() = Vector4i(this.z, this.x, this.x, this.x)
val Vector3i.brrg get() = Vector4i(this.z, this.x, this.x, this.y)
val Vector3i.brrb get() = Vector4i(this.z, this.x, this.x, this.z)
val Vector3i.brgr get() = Vector4i(this.z, this.x, this.y, this.x)
val Vector3i.brgg get() = Vector4i(this.z, this.x, this.y, this.y)
val Vector3i.brgb get() = Vector4i(this.z, this.x, this.y, this.z)
val Vector3i.brbr get() = Vector4i(this.z, this.x, this.z, this.x)
val Vector3i.brbg get() = Vector4i(this.z, this.x, this.z, this.y)
val Vector3i.brbb get() = Vector4i(this.z, this.x, this.z, this.z)
val Vector3i.bgrr get() = Vector4i(this.z, this.y, this.x, this.x)
val Vector3i.bgrg get() = Vector4i(this.z, this.y, this.x, this.y)
val Vector3i.bgrb get() = Vector4i(this.z, this.y, this.x, this.z)
val Vector3i.bggr get() = Vector4i(this.z, this.y, this.y, this.x)
val Vector3i.bggg get() = Vector4i(this.z, this.y, this.y, this.y)
val Vector3i.bggb get() = Vector4i(this.z, this.y, this.y, this.z)
val Vector3i.bgbr get() = Vector4i(this.z, this.y, this.z, this.x)
val Vector3i.bgbg get() = Vector4i(this.z, this.y, this.z, this.y)
val Vector3i.bgbb get() = Vector4i(this.z, this.y, this.z, this.z)
val Vector3i.bbrr get() = Vector4i(this.z, this.z, this.x, this.x)
val Vector3i.bbrg get() = Vector4i(this.z, this.z, this.x, this.y)
val Vector3i.bbrb get() = Vector4i(this.z, this.z, this.x, this.z)
val Vector3i.bbgr get() = Vector4i(this.z, this.z, this.y, this.x)
val Vector3i.bbgg get() = Vector4i(this.z, this.z, this.y, this.y)
val Vector3i.bbgb get() = Vector4i(this.z, this.z, this.y, this.z)
val Vector3i.bbbr get() = Vector4i(this.z, this.z, this.z, this.x)
val Vector3i.bbbg get() = Vector4i(this.z, this.z, this.z, this.y)
val Vector3i.bbbb get() = Vector4i(this.z, this.z, this.z, this.z)