@file:Suppress("unused", "SpellCheckingInspection")
package com.losi.create.utility.joml

import org.joml.*

fun Vector3l.toTriple() = Triple(this.x, this.y, this.z)
fun Triple<Long, Long, Long>.toVector() = Vector3l(this.first, this.second, this.third)

// ===================================== XYZ =====================================
val Vector3l.xx get() = Vector2l(this.x, this.x)
var Vector3l.xy get() = Vector2l(this.x, this.y); set(v) { this.x = v.x; this.y = v.y }
var Vector3l.xz get() = Vector2l(this.x, this.z); set(v) { this.x = v.x; this.z = v.y }
var Vector3l.yx get() = Vector2l(this.y, this.x); set(v) { this.y = v.x; this.x = v.y }
val Vector3l.yy get() = Vector2l(this.y, this.y)
var Vector3l.yz get() = Vector2l(this.y, this.z); set(v) { this.y = v.x; this.z = v.y }
var Vector3l.zx get() = Vector2l(this.z, this.x); set(v) { this.z = v.x; this.x = v.y }
var Vector3l.zy get() = Vector2l(this.z, this.y); set(v) { this.z = v.x; this.y = v.y }
val Vector3l.zz get() = Vector2l(this.z, this.z)

val Vector3l.xxx get() = Vector3l(this.x, this.x, this.x)
val Vector3l.xxy get() = Vector3l(this.x, this.x, this.y)
val Vector3l.xxz get() = Vector3l(this.x, this.x, this.z)
val Vector3l.xyx get() = Vector3l(this.x, this.y, this.x)
val Vector3l.xyy get() = Vector3l(this.x, this.y, this.y)
var Vector3l.xyz get() = Vector3l(this.x, this.y, this.z); set(v) { this.x = v.x; this.y = v.y; this.z = v.z }
val Vector3l.xzx get() = Vector3l(this.x, this.z, this.x)
var Vector3l.xzy get() = Vector3l(this.x, this.z, this.y); set(v) { this.x = v.x; this.z = v.y; this.y = v.z }
val Vector3l.xzz get() = Vector3l(this.x, this.z, this.z)
val Vector3l.yxx get() = Vector3l(this.y, this.x, this.x)
val Vector3l.yxy get() = Vector3l(this.y, this.x, this.y)
var Vector3l.yxz get() = Vector3l(this.y, this.x, this.z); set(v) { this.y = v.x; this.x = v.y; this.z = v.z }
val Vector3l.yyx get() = Vector3l(this.y, this.y, this.x)
val Vector3l.yyy get() = Vector3l(this.y, this.y, this.y)
val Vector3l.yyz get() = Vector3l(this.y, this.y, this.z)
var Vector3l.yzx get() = Vector3l(this.y, this.z, this.x); set(v) { this.y = v.x; this.z = v.y; this.x = v.z }
val Vector3l.yzy get() = Vector3l(this.y, this.z, this.y)
val Vector3l.yzz get() = Vector3l(this.y, this.z, this.z)
val Vector3l.zxx get() = Vector3l(this.z, this.x, this.x)
var Vector3l.zxy get() = Vector3l(this.z, this.x, this.y); set(v) { this.z = v.x; this.x = v.y; this.y = v.z }
val Vector3l.zxz get() = Vector3l(this.z, this.x, this.z)
var Vector3l.zyx get() = Vector3l(this.z, this.y, this.x); set(v) { this.z = v.x; this.y = v.y; this.x = v.z }
val Vector3l.zyy get() = Vector3l(this.z, this.y, this.y)
val Vector3l.zyz get() = Vector3l(this.z, this.y, this.z)
val Vector3l.zzx get() = Vector3l(this.z, this.z, this.x)
val Vector3l.zzy get() = Vector3l(this.z, this.z, this.y)
val Vector3l.zzz get() = Vector3l(this.z, this.z, this.z)

val Vector3l.xxxx get() = Vector4l(this.x, this.x, this.x, this.x)
val Vector3l.xxxy get() = Vector4l(this.x, this.x, this.x, this.y)
val Vector3l.xxxz get() = Vector4l(this.x, this.x, this.x, this.z)
val Vector3l.xxyx get() = Vector4l(this.x, this.x, this.y, this.x)
val Vector3l.xxyy get() = Vector4l(this.x, this.x, this.y, this.y)
val Vector3l.xxyz get() = Vector4l(this.x, this.x, this.y, this.z)
val Vector3l.xxzx get() = Vector4l(this.x, this.x, this.z, this.x)
val Vector3l.xxzy get() = Vector4l(this.x, this.x, this.z, this.y)
val Vector3l.xxzz get() = Vector4l(this.x, this.x, this.z, this.z)
val Vector3l.xyxx get() = Vector4l(this.x, this.y, this.x, this.x)
val Vector3l.xyxy get() = Vector4l(this.x, this.y, this.x, this.y)
val Vector3l.xyxz get() = Vector4l(this.x, this.y, this.x, this.z)
val Vector3l.xyyx get() = Vector4l(this.x, this.y, this.y, this.x)
val Vector3l.xyyy get() = Vector4l(this.x, this.y, this.y, this.y)
val Vector3l.xyyz get() = Vector4l(this.x, this.y, this.y, this.z)
val Vector3l.xyzx get() = Vector4l(this.x, this.y, this.z, this.x)
val Vector3l.xyzy get() = Vector4l(this.x, this.y, this.z, this.y)
val Vector3l.xyzz get() = Vector4l(this.x, this.y, this.z, this.z)
val Vector3l.xzxx get() = Vector4l(this.x, this.z, this.x, this.x)
val Vector3l.xzxy get() = Vector4l(this.x, this.z, this.x, this.y)
val Vector3l.xzxz get() = Vector4l(this.x, this.z, this.x, this.z)
val Vector3l.xzyx get() = Vector4l(this.x, this.z, this.y, this.x)
val Vector3l.xzyy get() = Vector4l(this.x, this.z, this.y, this.y)
val Vector3l.xzyz get() = Vector4l(this.x, this.z, this.y, this.z)
val Vector3l.xzzx get() = Vector4l(this.x, this.z, this.z, this.x)
val Vector3l.xzzy get() = Vector4l(this.x, this.z, this.z, this.y)
val Vector3l.xzzz get() = Vector4l(this.x, this.z, this.z, this.z)
val Vector3l.yxxx get() = Vector4l(this.y, this.x, this.x, this.x)
val Vector3l.yxxy get() = Vector4l(this.y, this.x, this.x, this.y)
val Vector3l.yxxz get() = Vector4l(this.y, this.x, this.x, this.z)
val Vector3l.yxyx get() = Vector4l(this.y, this.x, this.y, this.x)
val Vector3l.yxyy get() = Vector4l(this.y, this.x, this.y, this.y)
val Vector3l.yxyz get() = Vector4l(this.y, this.x, this.y, this.z)
val Vector3l.yxzx get() = Vector4l(this.y, this.x, this.z, this.x)
val Vector3l.yxzy get() = Vector4l(this.y, this.x, this.z, this.y)
val Vector3l.yxzz get() = Vector4l(this.y, this.x, this.z, this.z)
val Vector3l.yyxx get() = Vector4l(this.y, this.y, this.x, this.x)
val Vector3l.yyxy get() = Vector4l(this.y, this.y, this.x, this.y)
val Vector3l.yyxz get() = Vector4l(this.y, this.y, this.x, this.z)
val Vector3l.yyyx get() = Vector4l(this.y, this.y, this.y, this.x)
val Vector3l.yyyy get() = Vector4l(this.y, this.y, this.y, this.y)
val Vector3l.yyyz get() = Vector4l(this.y, this.y, this.y, this.z)
val Vector3l.yyzx get() = Vector4l(this.y, this.y, this.z, this.x)
val Vector3l.yyzy get() = Vector4l(this.y, this.y, this.z, this.y)
val Vector3l.yyzz get() = Vector4l(this.y, this.y, this.z, this.z)
val Vector3l.yzxx get() = Vector4l(this.y, this.z, this.x, this.x)
val Vector3l.yzxy get() = Vector4l(this.y, this.z, this.x, this.y)
val Vector3l.yzxz get() = Vector4l(this.y, this.z, this.x, this.z)
val Vector3l.yzyx get() = Vector4l(this.y, this.z, this.y, this.x)
val Vector3l.yzyy get() = Vector4l(this.y, this.z, this.y, this.y)
val Vector3l.yzyz get() = Vector4l(this.y, this.z, this.y, this.z)
val Vector3l.yzzx get() = Vector4l(this.y, this.z, this.z, this.x)
val Vector3l.yzzy get() = Vector4l(this.y, this.z, this.z, this.y)
val Vector3l.yzzz get() = Vector4l(this.y, this.z, this.z, this.z)
val Vector3l.zxxx get() = Vector4l(this.z, this.x, this.x, this.x)
val Vector3l.zxxy get() = Vector4l(this.z, this.x, this.x, this.y)
val Vector3l.zxxz get() = Vector4l(this.z, this.x, this.x, this.z)
val Vector3l.zxyx get() = Vector4l(this.z, this.x, this.y, this.x)
val Vector3l.zxyy get() = Vector4l(this.z, this.x, this.y, this.y)
val Vector3l.zxyz get() = Vector4l(this.z, this.x, this.y, this.z)
val Vector3l.zxzx get() = Vector4l(this.z, this.x, this.z, this.x)
val Vector3l.zxzy get() = Vector4l(this.z, this.x, this.z, this.y)
val Vector3l.zxzz get() = Vector4l(this.z, this.x, this.z, this.z)
val Vector3l.zyxx get() = Vector4l(this.z, this.y, this.x, this.x)
val Vector3l.zyxy get() = Vector4l(this.z, this.y, this.x, this.y)
val Vector3l.zyxz get() = Vector4l(this.z, this.y, this.x, this.z)
val Vector3l.zyyx get() = Vector4l(this.z, this.y, this.y, this.x)
val Vector3l.zyyy get() = Vector4l(this.z, this.y, this.y, this.y)
val Vector3l.zyyz get() = Vector4l(this.z, this.y, this.y, this.z)
val Vector3l.zyzx get() = Vector4l(this.z, this.y, this.z, this.x)
val Vector3l.zyzy get() = Vector4l(this.z, this.y, this.z, this.y)
val Vector3l.zyzz get() = Vector4l(this.z, this.y, this.z, this.z)
val Vector3l.zzxx get() = Vector4l(this.z, this.z, this.x, this.x)
val Vector3l.zzxy get() = Vector4l(this.z, this.z, this.x, this.y)
val Vector3l.zzxz get() = Vector4l(this.z, this.z, this.x, this.z)
val Vector3l.zzyx get() = Vector4l(this.z, this.z, this.y, this.x)
val Vector3l.zzyy get() = Vector4l(this.z, this.z, this.y, this.y)
val Vector3l.zzyz get() = Vector4l(this.z, this.z, this.y, this.z)
val Vector3l.zzzx get() = Vector4l(this.z, this.z, this.z, this.x)
val Vector3l.zzzy get() = Vector4l(this.z, this.z, this.z, this.y)
val Vector3l.zzzz get() = Vector4l(this.z, this.z, this.z, this.z)

// ===================================== RGB =====================================
var Vector3l.r: Long get() = this.x; set(it) { this.x = it }
var Vector3l.g: Long get() = this.y; set(it) { this.y = it }
var Vector3l.b: Long get() = this.z; set(it) { this.z = it }

val Vector3l.rr get() = Vector2l(this.x, this.x)
var Vector3l.rg get() = Vector2l(this.x, this.y); set(v) { this.x = v.x; this.y = v.y }
var Vector3l.rb get() = Vector2l(this.x, this.z); set(v) { this.x = v.x; this.z = v.y }
var Vector3l.gr get() = Vector2l(this.y, this.x); set(v) { this.y = v.x; this.x = v.y }
val Vector3l.gg get() = Vector2l(this.y, this.y)
var Vector3l.gb get() = Vector2l(this.y, this.z); set(v) { this.y = v.x; this.z = v.y }
var Vector3l.br get() = Vector2l(this.z, this.x); set(v) { this.z = v.x; this.x = v.y }
var Vector3l.bg get() = Vector2l(this.z, this.y); set(v) { this.z = v.x; this.y = v.y }
val Vector3l.bb get() = Vector2l(this.z, this.z)

val Vector3l.rrr get() = Vector3l(this.x, this.x, this.x)
val Vector3l.rrg get() = Vector3l(this.x, this.x, this.y)
val Vector3l.rrb get() = Vector3l(this.x, this.x, this.z)
val Vector3l.rgr get() = Vector3l(this.x, this.y, this.x)
val Vector3l.rgg get() = Vector3l(this.x, this.y, this.y)
var Vector3l.rgb get() = Vector3l(this.x, this.y, this.z); set(v) { this.x = v.x; this.y = v.y; this.z = v.z }
val Vector3l.rbr get() = Vector3l(this.x, this.z, this.x)
var Vector3l.rbg get() = Vector3l(this.x, this.z, this.y); set(v) { this.x = v.x; this.z = v.y; this.y = v.z }
val Vector3l.rbb get() = Vector3l(this.x, this.z, this.z)
val Vector3l.grr get() = Vector3l(this.y, this.x, this.x)
val Vector3l.grg get() = Vector3l(this.y, this.x, this.y)
var Vector3l.grb get() = Vector3l(this.y, this.x, this.z); set(v) { this.y = v.x; this.x = v.y; this.z = v.z }
val Vector3l.ggr get() = Vector3l(this.y, this.y, this.x)
val Vector3l.ggg get() = Vector3l(this.y, this.y, this.y)
val Vector3l.ggb get() = Vector3l(this.y, this.y, this.z)
var Vector3l.gbr get() = Vector3l(this.y, this.z, this.x); set(v) { this.y = v.x; this.z = v.y; this.x = v.z }
val Vector3l.gbg get() = Vector3l(this.y, this.z, this.y)
val Vector3l.gbb get() = Vector3l(this.y, this.z, this.z)
val Vector3l.brr get() = Vector3l(this.z, this.x, this.x)
var Vector3l.brg get() = Vector3l(this.z, this.x, this.y); set(v) { this.z = v.x; this.x = v.y; this.y = v.z }
val Vector3l.brb get() = Vector3l(this.z, this.x, this.z)
var Vector3l.bgr get() = Vector3l(this.z, this.y, this.x); set(v) { this.z = v.x; this.y = v.y; this.x = v.z }
val Vector3l.bgg get() = Vector3l(this.z, this.y, this.y)
val Vector3l.bgb get() = Vector3l(this.z, this.y, this.z)
val Vector3l.bbr get() = Vector3l(this.z, this.z, this.x)
val Vector3l.bbg get() = Vector3l(this.z, this.z, this.y)
val Vector3l.bbb get() = Vector3l(this.z, this.z, this.z)

val Vector3l.rrrr get() = Vector4l(this.x, this.x, this.x, this.x)
val Vector3l.rrrg get() = Vector4l(this.x, this.x, this.x, this.y)
val Vector3l.rrrb get() = Vector4l(this.x, this.x, this.x, this.z)
val Vector3l.rrgr get() = Vector4l(this.x, this.x, this.y, this.x)
val Vector3l.rrgg get() = Vector4l(this.x, this.x, this.y, this.y)
val Vector3l.rrgb get() = Vector4l(this.x, this.x, this.y, this.z)
val Vector3l.rrbr get() = Vector4l(this.x, this.x, this.z, this.x)
val Vector3l.rrbg get() = Vector4l(this.x, this.x, this.z, this.y)
val Vector3l.rrbb get() = Vector4l(this.x, this.x, this.z, this.z)
val Vector3l.rgrr get() = Vector4l(this.x, this.y, this.x, this.x)
val Vector3l.rgrg get() = Vector4l(this.x, this.y, this.x, this.y)
val Vector3l.rgrb get() = Vector4l(this.x, this.y, this.x, this.z)
val Vector3l.rggr get() = Vector4l(this.x, this.y, this.y, this.x)
val Vector3l.rggg get() = Vector4l(this.x, this.y, this.y, this.y)
val Vector3l.rggb get() = Vector4l(this.x, this.y, this.y, this.z)
val Vector3l.rgbr get() = Vector4l(this.x, this.y, this.z, this.x)
val Vector3l.rgbg get() = Vector4l(this.x, this.y, this.z, this.y)
val Vector3l.rgbb get() = Vector4l(this.x, this.y, this.z, this.z)
val Vector3l.rbrr get() = Vector4l(this.x, this.z, this.x, this.x)
val Vector3l.rbrg get() = Vector4l(this.x, this.z, this.x, this.y)
val Vector3l.rbrb get() = Vector4l(this.x, this.z, this.x, this.z)
val Vector3l.rbgr get() = Vector4l(this.x, this.z, this.y, this.x)
val Vector3l.rbgg get() = Vector4l(this.x, this.z, this.y, this.y)
val Vector3l.rbgb get() = Vector4l(this.x, this.z, this.y, this.z)
val Vector3l.rbbr get() = Vector4l(this.x, this.z, this.z, this.x)
val Vector3l.rbbg get() = Vector4l(this.x, this.z, this.z, this.y)
val Vector3l.rbbb get() = Vector4l(this.x, this.z, this.z, this.z)
val Vector3l.grrr get() = Vector4l(this.y, this.x, this.x, this.x)
val Vector3l.grrg get() = Vector4l(this.y, this.x, this.x, this.y)
val Vector3l.grrb get() = Vector4l(this.y, this.x, this.x, this.z)
val Vector3l.grgr get() = Vector4l(this.y, this.x, this.y, this.x)
val Vector3l.grgg get() = Vector4l(this.y, this.x, this.y, this.y)
val Vector3l.grgb get() = Vector4l(this.y, this.x, this.y, this.z)
val Vector3l.grbr get() = Vector4l(this.y, this.x, this.z, this.x)
val Vector3l.grbg get() = Vector4l(this.y, this.x, this.z, this.y)
val Vector3l.grbb get() = Vector4l(this.y, this.x, this.z, this.z)
val Vector3l.ggrr get() = Vector4l(this.y, this.y, this.x, this.x)
val Vector3l.ggrg get() = Vector4l(this.y, this.y, this.x, this.y)
val Vector3l.ggrb get() = Vector4l(this.y, this.y, this.x, this.z)
val Vector3l.gggr get() = Vector4l(this.y, this.y, this.y, this.x)
val Vector3l.gggg get() = Vector4l(this.y, this.y, this.y, this.y)
val Vector3l.gggb get() = Vector4l(this.y, this.y, this.y, this.z)
val Vector3l.ggbr get() = Vector4l(this.y, this.y, this.z, this.x)
val Vector3l.ggbg get() = Vector4l(this.y, this.y, this.z, this.y)
val Vector3l.ggbb get() = Vector4l(this.y, this.y, this.z, this.z)
val Vector3l.gbrr get() = Vector4l(this.y, this.z, this.x, this.x)
val Vector3l.gbrg get() = Vector4l(this.y, this.z, this.x, this.y)
val Vector3l.gbrb get() = Vector4l(this.y, this.z, this.x, this.z)
val Vector3l.gbgr get() = Vector4l(this.y, this.z, this.y, this.x)
val Vector3l.gbgg get() = Vector4l(this.y, this.z, this.y, this.y)
val Vector3l.gbgb get() = Vector4l(this.y, this.z, this.y, this.z)
val Vector3l.gbbr get() = Vector4l(this.y, this.z, this.z, this.x)
val Vector3l.gbbg get() = Vector4l(this.y, this.z, this.z, this.y)
val Vector3l.gbbb get() = Vector4l(this.y, this.z, this.z, this.z)
val Vector3l.brrr get() = Vector4l(this.z, this.x, this.x, this.x)
val Vector3l.brrg get() = Vector4l(this.z, this.x, this.x, this.y)
val Vector3l.brrb get() = Vector4l(this.z, this.x, this.x, this.z)
val Vector3l.brgr get() = Vector4l(this.z, this.x, this.y, this.x)
val Vector3l.brgg get() = Vector4l(this.z, this.x, this.y, this.y)
val Vector3l.brgb get() = Vector4l(this.z, this.x, this.y, this.z)
val Vector3l.brbr get() = Vector4l(this.z, this.x, this.z, this.x)
val Vector3l.brbg get() = Vector4l(this.z, this.x, this.z, this.y)
val Vector3l.brbb get() = Vector4l(this.z, this.x, this.z, this.z)
val Vector3l.bgrr get() = Vector4l(this.z, this.y, this.x, this.x)
val Vector3l.bgrg get() = Vector4l(this.z, this.y, this.x, this.y)
val Vector3l.bgrb get() = Vector4l(this.z, this.y, this.x, this.z)
val Vector3l.bggr get() = Vector4l(this.z, this.y, this.y, this.x)
val Vector3l.bggg get() = Vector4l(this.z, this.y, this.y, this.y)
val Vector3l.bggb get() = Vector4l(this.z, this.y, this.y, this.z)
val Vector3l.bgbr get() = Vector4l(this.z, this.y, this.z, this.x)
val Vector3l.bgbg get() = Vector4l(this.z, this.y, this.z, this.y)
val Vector3l.bgbb get() = Vector4l(this.z, this.y, this.z, this.z)
val Vector3l.bbrr get() = Vector4l(this.z, this.z, this.x, this.x)
val Vector3l.bbrg get() = Vector4l(this.z, this.z, this.x, this.y)
val Vector3l.bbrb get() = Vector4l(this.z, this.z, this.x, this.z)
val Vector3l.bbgr get() = Vector4l(this.z, this.z, this.y, this.x)
val Vector3l.bbgg get() = Vector4l(this.z, this.z, this.y, this.y)
val Vector3l.bbgb get() = Vector4l(this.z, this.z, this.y, this.z)
val Vector3l.bbbr get() = Vector4l(this.z, this.z, this.z, this.x)
val Vector3l.bbbg get() = Vector4l(this.z, this.z, this.z, this.y)
val Vector3l.bbbb get() = Vector4l(this.z, this.z, this.z, this.z)