@file:Suppress("unused", "SpellCheckingInspection")
package com.losi.create.utility.joml

import org.joml.*

fun Vector3d.toTriple() = Triple(this.x, this.y, this.z)
fun Triple<Double, Double, Double>.toVector() = Vector3d(this.first, this.second, this.third)

// ===================================== XYZ =====================================
val Vector3d.xx get() = Vector2d(this.x, this.x)
var Vector3d.xy get() = Vector2d(this.x, this.y); set(v) { this.x = v.x; this.y = v.y }
var Vector3d.xz get() = Vector2d(this.x, this.z); set(v) { this.x = v.x; this.z = v.y }
var Vector3d.yx get() = Vector2d(this.y, this.x); set(v) { this.y = v.x; this.x = v.y }
val Vector3d.yy get() = Vector2d(this.y, this.y)
var Vector3d.yz get() = Vector2d(this.y, this.z); set(v) { this.y = v.x; this.z = v.y }
var Vector3d.zx get() = Vector2d(this.z, this.x); set(v) { this.z = v.x; this.x = v.y }
var Vector3d.zy get() = Vector2d(this.z, this.y); set(v) { this.z = v.x; this.y = v.y }
val Vector3d.zz get() = Vector2d(this.z, this.z)

val Vector3d.xxx get() = Vector3d(this.x, this.x, this.x)
val Vector3d.xxy get() = Vector3d(this.x, this.x, this.y)
val Vector3d.xxz get() = Vector3d(this.x, this.x, this.z)
val Vector3d.xyx get() = Vector3d(this.x, this.y, this.x)
val Vector3d.xyy get() = Vector3d(this.x, this.y, this.y)
var Vector3d.xyz get() = Vector3d(this.x, this.y, this.z); set(v) { this.x = v.x; this.y = v.y; this.z = v.z }
val Vector3d.xzx get() = Vector3d(this.x, this.z, this.x)
var Vector3d.xzy get() = Vector3d(this.x, this.z, this.y); set(v) { this.x = v.x; this.z = v.y; this.y = v.z }
val Vector3d.xzz get() = Vector3d(this.x, this.z, this.z)
val Vector3d.yxx get() = Vector3d(this.y, this.x, this.x)
val Vector3d.yxy get() = Vector3d(this.y, this.x, this.y)
var Vector3d.yxz get() = Vector3d(this.y, this.x, this.z); set(v) { this.y = v.x; this.x = v.y; this.z = v.z }
val Vector3d.yyx get() = Vector3d(this.y, this.y, this.x)
val Vector3d.yyy get() = Vector3d(this.y, this.y, this.y)
val Vector3d.yyz get() = Vector3d(this.y, this.y, this.z)
var Vector3d.yzx get() = Vector3d(this.y, this.z, this.x); set(v) { this.y = v.x; this.z = v.y; this.x = v.z }
val Vector3d.yzy get() = Vector3d(this.y, this.z, this.y)
val Vector3d.yzz get() = Vector3d(this.y, this.z, this.z)
val Vector3d.zxx get() = Vector3d(this.z, this.x, this.x)
var Vector3d.zxy get() = Vector3d(this.z, this.x, this.y); set(v) { this.z = v.x; this.x = v.y; this.y = v.z }
val Vector3d.zxz get() = Vector3d(this.z, this.x, this.z)
var Vector3d.zyx get() = Vector3d(this.z, this.y, this.x); set(v) { this.z = v.x; this.y = v.y; this.x = v.z }
val Vector3d.zyy get() = Vector3d(this.z, this.y, this.y)
val Vector3d.zyz get() = Vector3d(this.z, this.y, this.z)
val Vector3d.zzx get() = Vector3d(this.z, this.z, this.x)
val Vector3d.zzy get() = Vector3d(this.z, this.z, this.y)
val Vector3d.zzz get() = Vector3d(this.z, this.z, this.z)

val Vector3d.xxxx get() = Vector4d(this.x, this.x, this.x, this.x)
val Vector3d.xxxy get() = Vector4d(this.x, this.x, this.x, this.y)
val Vector3d.xxxz get() = Vector4d(this.x, this.x, this.x, this.z)
val Vector3d.xxyx get() = Vector4d(this.x, this.x, this.y, this.x)
val Vector3d.xxyy get() = Vector4d(this.x, this.x, this.y, this.y)
val Vector3d.xxyz get() = Vector4d(this.x, this.x, this.y, this.z)
val Vector3d.xxzx get() = Vector4d(this.x, this.x, this.z, this.x)
val Vector3d.xxzy get() = Vector4d(this.x, this.x, this.z, this.y)
val Vector3d.xxzz get() = Vector4d(this.x, this.x, this.z, this.z)
val Vector3d.xyxx get() = Vector4d(this.x, this.y, this.x, this.x)
val Vector3d.xyxy get() = Vector4d(this.x, this.y, this.x, this.y)
val Vector3d.xyxz get() = Vector4d(this.x, this.y, this.x, this.z)
val Vector3d.xyyx get() = Vector4d(this.x, this.y, this.y, this.x)
val Vector3d.xyyy get() = Vector4d(this.x, this.y, this.y, this.y)
val Vector3d.xyyz get() = Vector4d(this.x, this.y, this.y, this.z)
val Vector3d.xyzx get() = Vector4d(this.x, this.y, this.z, this.x)
val Vector3d.xyzy get() = Vector4d(this.x, this.y, this.z, this.y)
val Vector3d.xyzz get() = Vector4d(this.x, this.y, this.z, this.z)
val Vector3d.xzxx get() = Vector4d(this.x, this.z, this.x, this.x)
val Vector3d.xzxy get() = Vector4d(this.x, this.z, this.x, this.y)
val Vector3d.xzxz get() = Vector4d(this.x, this.z, this.x, this.z)
val Vector3d.xzyx get() = Vector4d(this.x, this.z, this.y, this.x)
val Vector3d.xzyy get() = Vector4d(this.x, this.z, this.y, this.y)
val Vector3d.xzyz get() = Vector4d(this.x, this.z, this.y, this.z)
val Vector3d.xzzx get() = Vector4d(this.x, this.z, this.z, this.x)
val Vector3d.xzzy get() = Vector4d(this.x, this.z, this.z, this.y)
val Vector3d.xzzz get() = Vector4d(this.x, this.z, this.z, this.z)
val Vector3d.yxxx get() = Vector4d(this.y, this.x, this.x, this.x)
val Vector3d.yxxy get() = Vector4d(this.y, this.x, this.x, this.y)
val Vector3d.yxxz get() = Vector4d(this.y, this.x, this.x, this.z)
val Vector3d.yxyx get() = Vector4d(this.y, this.x, this.y, this.x)
val Vector3d.yxyy get() = Vector4d(this.y, this.x, this.y, this.y)
val Vector3d.yxyz get() = Vector4d(this.y, this.x, this.y, this.z)
val Vector3d.yxzx get() = Vector4d(this.y, this.x, this.z, this.x)
val Vector3d.yxzy get() = Vector4d(this.y, this.x, this.z, this.y)
val Vector3d.yxzz get() = Vector4d(this.y, this.x, this.z, this.z)
val Vector3d.yyxx get() = Vector4d(this.y, this.y, this.x, this.x)
val Vector3d.yyxy get() = Vector4d(this.y, this.y, this.x, this.y)
val Vector3d.yyxz get() = Vector4d(this.y, this.y, this.x, this.z)
val Vector3d.yyyx get() = Vector4d(this.y, this.y, this.y, this.x)
val Vector3d.yyyy get() = Vector4d(this.y, this.y, this.y, this.y)
val Vector3d.yyyz get() = Vector4d(this.y, this.y, this.y, this.z)
val Vector3d.yyzx get() = Vector4d(this.y, this.y, this.z, this.x)
val Vector3d.yyzy get() = Vector4d(this.y, this.y, this.z, this.y)
val Vector3d.yyzz get() = Vector4d(this.y, this.y, this.z, this.z)
val Vector3d.yzxx get() = Vector4d(this.y, this.z, this.x, this.x)
val Vector3d.yzxy get() = Vector4d(this.y, this.z, this.x, this.y)
val Vector3d.yzxz get() = Vector4d(this.y, this.z, this.x, this.z)
val Vector3d.yzyx get() = Vector4d(this.y, this.z, this.y, this.x)
val Vector3d.yzyy get() = Vector4d(this.y, this.z, this.y, this.y)
val Vector3d.yzyz get() = Vector4d(this.y, this.z, this.y, this.z)
val Vector3d.yzzx get() = Vector4d(this.y, this.z, this.z, this.x)
val Vector3d.yzzy get() = Vector4d(this.y, this.z, this.z, this.y)
val Vector3d.yzzz get() = Vector4d(this.y, this.z, this.z, this.z)
val Vector3d.zxxx get() = Vector4d(this.z, this.x, this.x, this.x)
val Vector3d.zxxy get() = Vector4d(this.z, this.x, this.x, this.y)
val Vector3d.zxxz get() = Vector4d(this.z, this.x, this.x, this.z)
val Vector3d.zxyx get() = Vector4d(this.z, this.x, this.y, this.x)
val Vector3d.zxyy get() = Vector4d(this.z, this.x, this.y, this.y)
val Vector3d.zxyz get() = Vector4d(this.z, this.x, this.y, this.z)
val Vector3d.zxzx get() = Vector4d(this.z, this.x, this.z, this.x)
val Vector3d.zxzy get() = Vector4d(this.z, this.x, this.z, this.y)
val Vector3d.zxzz get() = Vector4d(this.z, this.x, this.z, this.z)
val Vector3d.zyxx get() = Vector4d(this.z, this.y, this.x, this.x)
val Vector3d.zyxy get() = Vector4d(this.z, this.y, this.x, this.y)
val Vector3d.zyxz get() = Vector4d(this.z, this.y, this.x, this.z)
val Vector3d.zyyx get() = Vector4d(this.z, this.y, this.y, this.x)
val Vector3d.zyyy get() = Vector4d(this.z, this.y, this.y, this.y)
val Vector3d.zyyz get() = Vector4d(this.z, this.y, this.y, this.z)
val Vector3d.zyzx get() = Vector4d(this.z, this.y, this.z, this.x)
val Vector3d.zyzy get() = Vector4d(this.z, this.y, this.z, this.y)
val Vector3d.zyzz get() = Vector4d(this.z, this.y, this.z, this.z)
val Vector3d.zzxx get() = Vector4d(this.z, this.z, this.x, this.x)
val Vector3d.zzxy get() = Vector4d(this.z, this.z, this.x, this.y)
val Vector3d.zzxz get() = Vector4d(this.z, this.z, this.x, this.z)
val Vector3d.zzyx get() = Vector4d(this.z, this.z, this.y, this.x)
val Vector3d.zzyy get() = Vector4d(this.z, this.z, this.y, this.y)
val Vector3d.zzyz get() = Vector4d(this.z, this.z, this.y, this.z)
val Vector3d.zzzx get() = Vector4d(this.z, this.z, this.z, this.x)
val Vector3d.zzzy get() = Vector4d(this.z, this.z, this.z, this.y)
val Vector3d.zzzz get() = Vector4d(this.z, this.z, this.z, this.z)

// ===================================== RGB =====================================
var Vector3d.r: Double get() = this.x; set(it) { this.x = it }
var Vector3d.g: Double get() = this.y; set(it) { this.y = it }
var Vector3d.b: Double get() = this.z; set(it) { this.z = it }

val Vector3d.rr get() = Vector2d(this.x, this.x)
var Vector3d.rg get() = Vector2d(this.x, this.y); set(v) { this.x = v.x; this.y = v.y }
var Vector3d.rb get() = Vector2d(this.x, this.z); set(v) { this.x = v.x; this.z = v.y }
var Vector3d.gr get() = Vector2d(this.y, this.x); set(v) { this.y = v.x; this.x = v.y }
val Vector3d.gg get() = Vector2d(this.y, this.y)
var Vector3d.gb get() = Vector2d(this.y, this.z); set(v) { this.y = v.x; this.z = v.y }
var Vector3d.br get() = Vector2d(this.z, this.x); set(v) { this.z = v.x; this.x = v.y }
var Vector3d.bg get() = Vector2d(this.z, this.y); set(v) { this.z = v.x; this.y = v.y }
val Vector3d.bb get() = Vector2d(this.z, this.z)

val Vector3d.rrr get() = Vector3d(this.x, this.x, this.x)
val Vector3d.rrg get() = Vector3d(this.x, this.x, this.y)
val Vector3d.rrb get() = Vector3d(this.x, this.x, this.z)
val Vector3d.rgr get() = Vector3d(this.x, this.y, this.x)
val Vector3d.rgg get() = Vector3d(this.x, this.y, this.y)
var Vector3d.rgb get() = Vector3d(this.x, this.y, this.z); set(v) { this.x = v.x; this.y = v.y; this.z = v.z }
val Vector3d.rbr get() = Vector3d(this.x, this.z, this.x)
var Vector3d.rbg get() = Vector3d(this.x, this.z, this.y); set(v) { this.x = v.x; this.z = v.y; this.y = v.z }
val Vector3d.rbb get() = Vector3d(this.x, this.z, this.z)
val Vector3d.grr get() = Vector3d(this.y, this.x, this.x)
val Vector3d.grg get() = Vector3d(this.y, this.x, this.y)
var Vector3d.grb get() = Vector3d(this.y, this.x, this.z); set(v) { this.y = v.x; this.x = v.y; this.z = v.z }
val Vector3d.ggr get() = Vector3d(this.y, this.y, this.x)
val Vector3d.ggg get() = Vector3d(this.y, this.y, this.y)
val Vector3d.ggb get() = Vector3d(this.y, this.y, this.z)
var Vector3d.gbr get() = Vector3d(this.y, this.z, this.x); set(v) { this.y = v.x; this.z = v.y; this.x = v.z }
val Vector3d.gbg get() = Vector3d(this.y, this.z, this.y)
val Vector3d.gbb get() = Vector3d(this.y, this.z, this.z)
val Vector3d.brr get() = Vector3d(this.z, this.x, this.x)
var Vector3d.brg get() = Vector3d(this.z, this.x, this.y); set(v) { this.z = v.x; this.x = v.y; this.y = v.z }
val Vector3d.brb get() = Vector3d(this.z, this.x, this.z)
var Vector3d.bgr get() = Vector3d(this.z, this.y, this.x); set(v) { this.z = v.x; this.y = v.y; this.x = v.z }
val Vector3d.bgg get() = Vector3d(this.z, this.y, this.y)
val Vector3d.bgb get() = Vector3d(this.z, this.y, this.z)
val Vector3d.bbr get() = Vector3d(this.z, this.z, this.x)
val Vector3d.bbg get() = Vector3d(this.z, this.z, this.y)
val Vector3d.bbb get() = Vector3d(this.z, this.z, this.z)

val Vector3d.rrrr get() = Vector4d(this.x, this.x, this.x, this.x)
val Vector3d.rrrg get() = Vector4d(this.x, this.x, this.x, this.y)
val Vector3d.rrrb get() = Vector4d(this.x, this.x, this.x, this.z)
val Vector3d.rrgr get() = Vector4d(this.x, this.x, this.y, this.x)
val Vector3d.rrgg get() = Vector4d(this.x, this.x, this.y, this.y)
val Vector3d.rrgb get() = Vector4d(this.x, this.x, this.y, this.z)
val Vector3d.rrbr get() = Vector4d(this.x, this.x, this.z, this.x)
val Vector3d.rrbg get() = Vector4d(this.x, this.x, this.z, this.y)
val Vector3d.rrbb get() = Vector4d(this.x, this.x, this.z, this.z)
val Vector3d.rgrr get() = Vector4d(this.x, this.y, this.x, this.x)
val Vector3d.rgrg get() = Vector4d(this.x, this.y, this.x, this.y)
val Vector3d.rgrb get() = Vector4d(this.x, this.y, this.x, this.z)
val Vector3d.rggr get() = Vector4d(this.x, this.y, this.y, this.x)
val Vector3d.rggg get() = Vector4d(this.x, this.y, this.y, this.y)
val Vector3d.rggb get() = Vector4d(this.x, this.y, this.y, this.z)
val Vector3d.rgbr get() = Vector4d(this.x, this.y, this.z, this.x)
val Vector3d.rgbg get() = Vector4d(this.x, this.y, this.z, this.y)
val Vector3d.rgbb get() = Vector4d(this.x, this.y, this.z, this.z)
val Vector3d.rbrr get() = Vector4d(this.x, this.z, this.x, this.x)
val Vector3d.rbrg get() = Vector4d(this.x, this.z, this.x, this.y)
val Vector3d.rbrb get() = Vector4d(this.x, this.z, this.x, this.z)
val Vector3d.rbgr get() = Vector4d(this.x, this.z, this.y, this.x)
val Vector3d.rbgg get() = Vector4d(this.x, this.z, this.y, this.y)
val Vector3d.rbgb get() = Vector4d(this.x, this.z, this.y, this.z)
val Vector3d.rbbr get() = Vector4d(this.x, this.z, this.z, this.x)
val Vector3d.rbbg get() = Vector4d(this.x, this.z, this.z, this.y)
val Vector3d.rbbb get() = Vector4d(this.x, this.z, this.z, this.z)
val Vector3d.grrr get() = Vector4d(this.y, this.x, this.x, this.x)
val Vector3d.grrg get() = Vector4d(this.y, this.x, this.x, this.y)
val Vector3d.grrb get() = Vector4d(this.y, this.x, this.x, this.z)
val Vector3d.grgr get() = Vector4d(this.y, this.x, this.y, this.x)
val Vector3d.grgg get() = Vector4d(this.y, this.x, this.y, this.y)
val Vector3d.grgb get() = Vector4d(this.y, this.x, this.y, this.z)
val Vector3d.grbr get() = Vector4d(this.y, this.x, this.z, this.x)
val Vector3d.grbg get() = Vector4d(this.y, this.x, this.z, this.y)
val Vector3d.grbb get() = Vector4d(this.y, this.x, this.z, this.z)
val Vector3d.ggrr get() = Vector4d(this.y, this.y, this.x, this.x)
val Vector3d.ggrg get() = Vector4d(this.y, this.y, this.x, this.y)
val Vector3d.ggrb get() = Vector4d(this.y, this.y, this.x, this.z)
val Vector3d.gggr get() = Vector4d(this.y, this.y, this.y, this.x)
val Vector3d.gggg get() = Vector4d(this.y, this.y, this.y, this.y)
val Vector3d.gggb get() = Vector4d(this.y, this.y, this.y, this.z)
val Vector3d.ggbr get() = Vector4d(this.y, this.y, this.z, this.x)
val Vector3d.ggbg get() = Vector4d(this.y, this.y, this.z, this.y)
val Vector3d.ggbb get() = Vector4d(this.y, this.y, this.z, this.z)
val Vector3d.gbrr get() = Vector4d(this.y, this.z, this.x, this.x)
val Vector3d.gbrg get() = Vector4d(this.y, this.z, this.x, this.y)
val Vector3d.gbrb get() = Vector4d(this.y, this.z, this.x, this.z)
val Vector3d.gbgr get() = Vector4d(this.y, this.z, this.y, this.x)
val Vector3d.gbgg get() = Vector4d(this.y, this.z, this.y, this.y)
val Vector3d.gbgb get() = Vector4d(this.y, this.z, this.y, this.z)
val Vector3d.gbbr get() = Vector4d(this.y, this.z, this.z, this.x)
val Vector3d.gbbg get() = Vector4d(this.y, this.z, this.z, this.y)
val Vector3d.gbbb get() = Vector4d(this.y, this.z, this.z, this.z)
val Vector3d.brrr get() = Vector4d(this.z, this.x, this.x, this.x)
val Vector3d.brrg get() = Vector4d(this.z, this.x, this.x, this.y)
val Vector3d.brrb get() = Vector4d(this.z, this.x, this.x, this.z)
val Vector3d.brgr get() = Vector4d(this.z, this.x, this.y, this.x)
val Vector3d.brgg get() = Vector4d(this.z, this.x, this.y, this.y)
val Vector3d.brgb get() = Vector4d(this.z, this.x, this.y, this.z)
val Vector3d.brbr get() = Vector4d(this.z, this.x, this.z, this.x)
val Vector3d.brbg get() = Vector4d(this.z, this.x, this.z, this.y)
val Vector3d.brbb get() = Vector4d(this.z, this.x, this.z, this.z)
val Vector3d.bgrr get() = Vector4d(this.z, this.y, this.x, this.x)
val Vector3d.bgrg get() = Vector4d(this.z, this.y, this.x, this.y)
val Vector3d.bgrb get() = Vector4d(this.z, this.y, this.x, this.z)
val Vector3d.bggr get() = Vector4d(this.z, this.y, this.y, this.x)
val Vector3d.bggg get() = Vector4d(this.z, this.y, this.y, this.y)
val Vector3d.bggb get() = Vector4d(this.z, this.y, this.y, this.z)
val Vector3d.bgbr get() = Vector4d(this.z, this.y, this.z, this.x)
val Vector3d.bgbg get() = Vector4d(this.z, this.y, this.z, this.y)
val Vector3d.bgbb get() = Vector4d(this.z, this.y, this.z, this.z)
val Vector3d.bbrr get() = Vector4d(this.z, this.z, this.x, this.x)
val Vector3d.bbrg get() = Vector4d(this.z, this.z, this.x, this.y)
val Vector3d.bbrb get() = Vector4d(this.z, this.z, this.x, this.z)
val Vector3d.bbgr get() = Vector4d(this.z, this.z, this.y, this.x)
val Vector3d.bbgg get() = Vector4d(this.z, this.z, this.y, this.y)
val Vector3d.bbgb get() = Vector4d(this.z, this.z, this.y, this.z)
val Vector3d.bbbr get() = Vector4d(this.z, this.z, this.z, this.x)
val Vector3d.bbbg get() = Vector4d(this.z, this.z, this.z, this.y)
val Vector3d.bbbb get() = Vector4d(this.z, this.z, this.z, this.z)