<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ApplicationIcon>Resources\Icon.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\**\*" />
        <EmbeddedResource Update="@(EmbeddedResource)">
            <LogicalName>$([System.String]::Copy('%(RecursiveDir)').Replace('\','/'))%(Filename)%(Extension)</LogicalName>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Arch" Version="2.1.0" PrivateAssets="all" />
      <PackageReference Include="CodeOfChaos.Unions" Version="6.7.1" />
      <PackageReference Include="CodeOfChaos.Unions.Generators" Version="6.7.1">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Ico.Reader" Version="1.2.5" PrivateAssets="all" />
      <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" PrivateAssets="all" />
      <PackageReference Include="Nerdbank.MessagePack" Version="1.2.30" PrivateAssets="all" />
      <PackageReference Include="Serilog" Version="4.4.0-dev-02437" PrivateAssets="all" />
      <PackageReference Include="Silk.NET" Version="2.23.0" PrivateAssets="all" />
      <PackageReference Include="Silk.NET.Direct3D.Compilers" Version="2.23.0" PrivateAssets="all" />
      <PackageReference Include="Silk.NET.Direct3D11" Version="2.23.0" PrivateAssets="all" />
      <PackageReference Include="Silk.NET.Direct3D12" Version="2.23.0" PrivateAssets="all" />
      <PackageReference Include="Silk.NET.Input.Extensions" Version="2.23.0" PrivateAssets="all" />
      <PackageReference Include="Silk.NET.OpenGL.Extensions.ARB" Version="2.23.0" PrivateAssets="all" />
      <PackageReference Include="Silk.NET.SPIRV.Cross" Version="2.23.0" PrivateAssets="all" />
      <PackageReference Include="Silk.NET.SPIRV.Reflect" Version="2.23.0" PrivateAssets="all" />
      <PackageReference Include="StbImageSharp" Version="2.30.15" PrivateAssets="all" />
      <PackageReference Include="System.Text.Json" Version="11.0.0-preview.5.26302.115" PrivateAssets="all" />
      <PackageReference Include="JoltPhysicsSharp" Version="2.21.0" />
      <PackageReference Include="Silk.NET.Maths" Version="2.23.0" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="**\*.*.cs">
            <DependentUpon>$([System.String]::Copy('%(Filename)').Split('.')[0]).cs</DependentUpon>
        </Compile>
    </ItemGroup>

</Project>
