<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>14</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PackageLicenseUrl>https://github.com/Losi-pl/Create/blob/4481b55c5a2205765544f90f4c016859bd69b969/LICENSE</PackageLicenseUrl>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Create.OpenGL\Create.OpenGL.csproj">
      <Private>True</Private>
      <PrivateAssets></PrivateAssets>
    </ProjectReference>
    <ProjectReference Include="..\Create.Resource\Create.Resource.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Create.SourceGenerators\Create.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OneOf" Version="3.0.271" PrivateAssets="compile" />
    <PackageReference Include="OneOf.SourceGenerator" Version="3.0.271" PrivateAssets="compile" />
  </ItemGroup>

</Project>
