using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Reflection;
using System.Runtime.InteropServices.ComTypes;
using System.Security.Claims;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Create.SourceGenerators
{
    [Generator(LanguageNames.CSharp)]
    internal class RegisterElements : IIncrementalGenerator
    {
        public static readonly DiagnosticDescriptor UnsupportedType =
            new DiagnosticDescriptor(
                id: "CR001",
                title: "Unsupported Type",
                messageFormat: "Type {0} isn't supported by method Create.Mod.RegisterElement()",
                category: "Usage",
                defaultSeverity: DiagnosticSeverity.Error,
                isEnabledByDefault: true);

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterSourceOutput(context.CompilationProvider, (contex, compiler) =>
            {
                try
                {
                    var classNodes = compiler.SyntaxTrees.SelectMany(t =>
                       t.GetRoot()
                        .DescendantNodes()
                        .OfType<ClassDeclarationSyntax>()
                        .Where(c => c.AttributeLists.Count > 0)
                        .SelectMany(Class => Class.AttributeLists.Select(a => (a, Class)))
                        .SelectMany(a => a.a.Attributes.Select(Attr => (Attr, a.Class)))).ToArray()
                        .Where(a => compiler
                            .GetSemanticModel(a.Attr.SyntaxTree)
                            .GetTypeInfo(a.Attr).Type
                            .ToDisplayString() == "Create.SourceGenerators.RegisterAttribute");

                    var allowedTypes = GetClassParts(compiler, "Create", "Mod").SelectMany(c =>
                       c.Members.OfType<MethodDeclarationSyntax>()
                        .Where(m => m.Identifier.Text == "RegisterElement"))
                        .Select(m => m.ParameterList.Parameters[1].Type)
                        .Select(t => compiler.GetSemanticModel(t.SyntaxTree).GetTypeInfo(t).Type).ToArray();

                    StringBuilder sb = new StringBuilder();
                    sb.Append(@"// <auto-generated/>
                    namespace Create.SourceGenerators
                    {
                        internal static class Registers
                        {".Replace("                    ", ""));
                    bool any = false;
                    foreach (var cl in classNodes)
                    {
                        var full_name = GetFullyQualifiedName(cl.Class, compiler);
                        var source = (cl.Attr.ArgumentList.Arguments[0].Expression as TypeOfExpressionSyntax).Type;
                        var type = compiler.GetSemanticModel(source.SyntaxTree).GetTypeInfo(source).Type;
                        if (!allowedTypes.Any(t => SymbolEqualityComparer.Default.Equals(t, type)))
                        {
                            var error = Diagnostic.Create(UnsupportedType, cl.Attr.GetLocation(), type.ToDisplayString());
                            contex.ReportDiagnostic(error);
                            continue;
                        }
                        sb.Append($"\n        // Class: {full_name}, {type.ToDisplayString()}\n        public static void Load{type.Name}s(Create.Mod mod)\n        {{\n");
                        bool contentAny = false;



                        foreach (var pr in GetClassParts(compiler, cl.Class).SelectMany(c => c.Members).OfType<FieldDeclarationSyntax>().Where(node =>
                            node.Modifiers.Any(modifier => modifier.IsKind(SyntaxKind.PublicKeyword)) &&
                            node.Modifiers.Any(modifier => modifier.IsKind(SyntaxKind.StaticKeyword)) &&
                            node.Modifiers.Any(modifier => modifier.IsKind(SyntaxKind.ReadOnlyKeyword)))
                                .SelectMany(f => f.Declaration.Variables))
                        {
                            var dec = pr.Parent.Parent as FieldDeclarationSyntax;
                            var fieldType = compiler.GetSemanticModel(dec.Declaration.Type.SyntaxTree)
                                .GetTypeInfo(dec.Declaration.Type).Type;
                            if (!SymbolEqualityComparer.Default.Equals(fieldType, type))
                                continue;
                            string name = null;
                            bool ignore = false;
                            foreach (var attr in dec.AttributeLists.SelectMany(al => al.Attributes))
                            {
                                var typ = compiler.GetSemanticModel(attr.SyntaxTree)
                                    .GetTypeInfo(attr).Type
                                    .ToDisplayString();
                                if (typ == "Create.SourceGenerators.CustomNameAttribute")
                                {
                                    var ex = attr.ArgumentList.Arguments[0].Expression;
                                    var cons = compiler.GetSemanticModel(ex.SyntaxTree).GetConstantValue(ex);
                                    if (cons.Value as string == null)
                                        continue;
                                    var value = SyntaxFactory.LiteralExpression(
                                                    SyntaxKind.StringLiteralExpression,
                                                    SyntaxFactory.Literal(cons.Value as string))
                                                .ToString();
                                    name = value.Substring(1, value.Length - 2);
                                }
                                if (typ == "Create.SourceGenerators.IgnoreAttribute")
                                    ignore = true;
                            }
                            if (ignore)
                                continue;
                            name = name ?? pr.Identifier.Text
                                             .ToLower()
                                             .Replace('_', '-')
                                             .Replace("@", "");

                            sb.Append($"{(contentAny ? "\n" : string.Empty)}            mod.RegisterElement(\"{name}\", {full_name}.{pr.Identifier.Text});");
                            contentAny = true;
                        }
                        if (!contentAny)
                            sb.Append($"            // Class {full_name} doesn't yet have any elements to register");
                        sb.Append($"\n        }}");

                        any = true;
                    }
                    if (!any)
                        sb.Append("\n        // Here will be metods used to load elements during inicjalization");
                    sb.Append(@"
    }
}");
                    contex.AddSource("RegisterLoaders.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
                }
                catch (Exception ex)
                {
                    contex.AddSource("RegisterLoaders.g.cs", $@"// <auto-generated/>
namespace Create.SourceGenerators
{{
    internal static class Registers
    {{
        /* {ex.Message}*/
    }}
}}");
                }

            });

            context.RegisterPostInitializationOutput(ctx => ctx.AddSource($"RegisterAttributes.g.cs", SourceText.From(@"// <auto-generated/>
                namespace Create.SourceGenerators
                {
                    /// <summary>
                    /// Generuje metode do dodawania wrzystkich elementów w tej Klasie do rejestru
                    /// </summary>
                    [AttributeUsage(AttributeTargets.Class)]
                    public sealed class RegisterAttribute : Attribute
                    {
                        public RegisterAttribute(Type type) { }
                    }


                    /// <summary>
                    /// Ustawienie innej nazwy elementu
                    /// </summary>
                    [AttributeUsage(AttributeTargets.Field, AllowMultiple = false, Inherited = false)]
                    internal sealed class CustomNameAttribute : Attribute
                    {
                        public CustomNameAttribute(string name) { }
                    }
    
                    /// <summary>
                    /// Pominięcie w ładowaniu danego elementu
                    /// </summary>
                    [AttributeUsage(AttributeTargets.Field, AllowMultiple = false, Inherited = false)]
                    internal sealed class IgnoreAttribute : Attribute { }
                }".Replace("                ", ""), Encoding.UTF8)));
        }

        private string GetFullyQualifiedName(ClassDeclarationSyntax classDeclaration, Compilation compilation)
        {
            const string @global = "global::";
            var semanticModel = compilation.GetSemanticModel(classDeclaration.SyntaxTree);
            var classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration);
            string classFullName = classSymbol?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            if (classFullName.Remove(@global.Length) == global)
                classFullName = classFullName.Substring(@global.Length);
            return classFullName;
        }
        public IEnumerable<ClassDeclarationSyntax> GetClassParts(Compilation compilation, string @namespace, string name)
        {
            return compilation.SyntaxTrees
                .SelectMany(tree => tree.GetRoot().DescendantNodes())
                .Select(e => e is FileScopedNamespaceDeclarationSyntax fie ? 
                                    (fie.Name?.ToString() == @namespace ? e : null ) : 
                            (e is NamespaceDeclarationSyntax nam ? 
                                    (nam.Name?.ToString() == @namespace ? e : null) : null))
                .Where(o => o != null)
                .SelectMany(ns =>
                {
                    if(ns is FileScopedNamespaceDeclarationSyntax file)
                        return file.Members;
                    else if (ns is NamespaceDeclarationSyntax norm)
                        return norm.Members;
                    return Enumerable.Empty<MemberDeclarationSyntax>();
                })
                .OfType<ClassDeclarationSyntax>()
                .Where(c => c.Identifier.Text == name);
        }
        public IEnumerable<ClassDeclarationSyntax> GetClassParts(Compilation compilation, ClassDeclarationSyntax @class)
        {
            var @namespace = @class.Parent is FileScopedNamespaceDeclarationSyntax file1 ?
                                 (file1.Name?.ToString() ?? string.Empty) :
                             @class.Parent is NamespaceDeclarationSyntax nam1 ?
                                 (nam1.Name?.ToString() ?? string.Empty) : string.Empty;

            return compilation.SyntaxTrees
                .SelectMany(tree => tree.GetRoot().DescendantNodes())
                .Select(e => e is FileScopedNamespaceDeclarationSyntax fie2 ?
                                    (fie2.Name?.ToString() == @namespace ? e : null) :
                            (e is NamespaceDeclarationSyntax nam2 ?
                                    (nam2.Name?.ToString() == @namespace ? e : null) : null))
                .Where(o => o != null)
                .SelectMany(ns =>
                {
                    if (ns is FileScopedNamespaceDeclarationSyntax file)
                        return file.Members;
                    else if (ns is NamespaceDeclarationSyntax norm)
                        return norm.Members;
                    return Enumerable.Empty<MemberDeclarationSyntax>();
                })
                .OfType<ClassDeclarationSyntax>()
                .Where(c => c.Identifier.Text == @class.Identifier.Text);
        }
    }
}
